/**
 * AUTO-GENERATED by scripts/generate-client-data.ts — DO NOT EDIT MANUALLY.
 * Regenerate: npx tsx scripts/generate-client-data.ts
 * Generated: 2026-04-17
 *
 * Lightweight rechner data for client components (Footer, Header, SearchBar).
 * Excludes heavy fields: erklaerung (~600 words each), faq, formel, beispiel,
 * metaTitle, metaDescription — saving ~900 KB from the client bundle.
 */

export interface RechnerLight {
  slug: string;
  titel: string;
  beschreibung: string;
  kategorie: string;
  kategorieSlug: string;
  keywords: string[];
  icon: string;
}

export interface KategorieConfig {
  slug: string;
  name: string;
  beschreibung: string;
  icon: string;
  metaTitle: string;
  metaDescription: string;
}

export const kategorien: KategorieConfig[] = [
  {
    "slug": "alltag",
    "name": "Alltag",
    "beschreibung": "Praktische Rechner für den Alltag: Prozente, Einheiten, Rabatte und mehr.",
    "icon": "📋",
    "metaTitle": "Alltags-Rechner | Rechenfix.de",
    "metaDescription": "Kostenlose Online-Rechner für den Alltag: Prozentrechner, Einheitenumrechner, Rabattrechner und mehr. Sofort berechnen ohne Anmeldung."
  },
  {
    "slug": "finanzen",
    "name": "Finanzen",
    "beschreibung": "Finanzrechner für Gehalt, Steuern, Kredite und Investitionen.",
    "icon": "💰",
    "metaTitle": "Finanz-Rechner | Rechenfix.de",
    "metaDescription": "Kostenlose Online-Finanzrechner: Brutto-Netto, MwSt, Kreditrechner und mehr. Sofort berechnen ohne Anmeldung."
  },
  {
    "slug": "gesundheit",
    "name": "Gesundheit",
    "beschreibung": "Gesundheitsrechner: BMI, Kalorienbedarf, Idealgewicht und mehr.",
    "icon": "💚",
    "metaTitle": "Gesundheits-Rechner | Rechenfix.de",
    "metaDescription": "Kostenlose Online-Gesundheitsrechner: BMI, Kalorienbedarf, Idealgewicht und mehr. Sofort berechnen ohne Anmeldung."
  },
  {
    "slug": "auto",
    "name": "Auto & Verkehr",
    "beschreibung": "Rechner rund ums Auto: Spritkosten, Fahrtkosten, Kfz-Steuer und mehr.",
    "icon": "🚗",
    "metaTitle": "Auto-Rechner | Rechenfix.de",
    "metaDescription": "Kostenlose Online-Rechner für Auto & Verkehr: Spritkosten, Fahrtkosten und mehr. Sofort berechnen ohne Anmeldung."
  },
  {
    "slug": "wohnen",
    "name": "Wohnen & Energie",
    "beschreibung": "Rechner für Miete, Nebenkosten, Strom, Heizung und Immobilien.",
    "icon": "🏠",
    "metaTitle": "Wohnen & Energie Rechner | Rechenfix.de",
    "metaDescription": "Kostenlose Online-Rechner für Wohnen & Energie: Mietrechner, Stromkosten, Heizkosten und mehr. Sofort berechnen ohne Anmeldung."
  },
  {
    "slug": "mathe",
    "name": "Mathe & Schule",
    "beschreibung": "Mathematik-Rechner für Schule, Studium und Alltag: Brüche, Gleichungen und mehr.",
    "icon": "🎓",
    "metaTitle": "Mathe-Rechner | Rechenfix.de",
    "metaDescription": "Kostenlose Online-Mathe-Rechner für Schule und Studium: Bruchrechner, Gleichungen und mehr. Sofort berechnen ohne Anmeldung."
  },
  {
    "slug": "arbeit",
    "name": "Arbeit & Recht",
    "beschreibung": "Rechner für Arbeitszeit, Urlaubstage, Kündigungsfristen und mehr.",
    "icon": "💼",
    "metaTitle": "Arbeit & Recht Rechner | Rechenfix.de",
    "metaDescription": "Kostenlose Online-Rechner für Arbeit & Recht: Arbeitszeit, Urlaubstage und mehr. Sofort berechnen ohne Anmeldung."
  },
  {
    "slug": "kochen",
    "name": "Kochen & Ernährung",
    "beschreibung": "Rechner rund ums Kochen und Backen: Rezept skalieren, Cups umrechnen und mehr.",
    "icon": "🍳",
    "metaTitle": "Kochen & Ernährung Rechner | Rechenfix.de",
    "metaDescription": "Kostenlose Online-Rechner für Kochen & Ernährung: Rezept-Umrechner, Cups in Gramm, Portionen skalieren. Sofort berechnen ohne Anmeldung."
  },
  {
    "slug": "sport",
    "name": "Sport & Fitness",
    "beschreibung": "Rechner für Läufer und Sportler: Pace, Trainingszonen, Herzfrequenz und mehr.",
    "icon": "🏃",
    "metaTitle": "Sport & Fitness Rechner | Rechenfix.de",
    "metaDescription": "Kostenlose Online-Rechner für Sport & Fitness: Pace-Rechner, Herzfrequenz-Zonen, Trainingsintensität. Sofort berechnen ohne Anmeldung."
  }
];

export const rechner: RechnerLight[] = [
  {
    "slug": "prozentrechner",
    "titel": "Prozentrechner",
    "beschreibung": "Prozente berechnen: Prozentwert, Grundwert, Prozentsatz, Aufschlag & Rabatt — mit Rechenweg.",
    "kategorie": "Alltag",
    "kategorieSlug": "alltag",
    "keywords": [
      "prozentrechner",
      "prozent berechnen",
      "prozentwert berechnen",
      "grundwert berechnen",
      "prozentsatz berechnen",
      "prozentualer aufschlag",
      "rabatt berechnen",
      "prozentrechnung formel",
      "wie viel prozent",
      "prozent ausrechnen"
    ],
    "icon": "%"
  },
  {
    "slug": "dreisatz-rechner",
    "titel": "Dreisatzrechner",
    "beschreibung": "Dreisatz online berechnen: proportional und antiproportional, mit Rechenweg Schritt für Schritt.",
    "kategorie": "Alltag",
    "kategorieSlug": "alltag",
    "keywords": [
      "dreisatzrechner",
      "dreisatz berechnen",
      "dreisatz online",
      "proportional",
      "antiproportional",
      "dreisatz formel"
    ],
    "icon": "⚖️"
  },
  {
    "slug": "tagerechner",
    "titel": "Tagerechner",
    "beschreibung": "Tage zwischen zwei Daten berechnen: Kalendertage, Arbeitstage, Wochen und Monate auf einen Blick.",
    "kategorie": "Alltag",
    "kategorieSlug": "alltag",
    "keywords": [
      "tagerechner",
      "tage berechnen",
      "tage zwischen zwei daten",
      "arbeitstage berechnen",
      "datum differenz",
      "tage zählen"
    ],
    "icon": "📅"
  },
  {
    "slug": "rabattrechner",
    "titel": "Rabattrechner",
    "beschreibung": "Rabatt berechnen: Endpreis, Ersparnis in Euro, Rabatt in Prozent & Doppelrabatt — mit Rechenweg.",
    "kategorie": "Alltag",
    "kategorieSlug": "alltag",
    "keywords": [
      "rabattrechner",
      "rabatt berechnen",
      "rabatt in euro",
      "endpreis berechnen",
      "doppelrabatt",
      "rabatt prozent",
      "ersparnis berechnen",
      "sale rechner",
      "angebot berechnen",
      "preisnachlass berechnen"
    ],
    "icon": "🏷️"
  },
  {
    "slug": "countdown",
    "titel": "Countdown-Rechner",
    "beschreibung": "Wie viele Tage bis Weihnachten, Ostern, Silvester oder Ihrem Geburtstag? Live-Countdown mit Sekunden-Anzeige.",
    "kategorie": "Alltag",
    "kategorieSlug": "alltag",
    "keywords": [
      "countdown rechner",
      "wie viele tage bis weihnachten",
      "tage bis ostern",
      "countdown silvester",
      "tage bis sommerferien",
      "tage zähler",
      "countdown timer",
      "tage bis geburtstag",
      "wie lange noch bis weihnachten",
      "countdown online"
    ],
    "icon": "⏳"
  },
  {
    "slug": "lebenszeit-rechner",
    "titel": "Lebenszeit-Rechner",
    "beschreibung": "Wie viele Tage haben Sie bereits gelebt? Überraschende Fakten über Ihre Lebenszeit, Herzschläge und verbleibende Wochenenden.",
    "kategorie": "Alltag",
    "kategorieSlug": "alltag",
    "keywords": [
      "lebenszeit rechner",
      "wie viele tage habe ich gelebt",
      "tage gelebt",
      "lebenserwartung rechner",
      "herzschläge berechnen",
      "wie alt bin ich in tagen",
      "lebenszeit statistik",
      "verbleibende lebenszeit",
      "alter in tagen",
      "lebensuhr"
    ],
    "icon": "🧬"
  },
  {
    "slug": "streaming-kosten-rechner",
    "titel": "Streaming-Kosten-Rechner",
    "beschreibung": "Berechnen Sie Ihre monatlichen Streaming-Kosten: Netflix, Disney+, Spotify und mehr auf einen Blick.",
    "kategorie": "Alltag",
    "kategorieSlug": "alltag",
    "keywords": [
      "streaming kosten rechner",
      "streaming abos kosten",
      "netflix kosten",
      "disney plus kosten",
      "spotify kosten",
      "streaming vergleich",
      "abo kosten berechnen",
      "streaming ausgaben",
      "was kosten meine abos",
      "streaming sparen"
    ],
    "icon": "📺"
  },
  {
    "slug": "kaffee-kosten-rechner",
    "titel": "Kaffee-Kosten-Rechner",
    "beschreibung": "Berechnen Sie Ihre täglichen, monatlichen und jährlichen Kaffeekosten — mit Spartipps und Vergleichen.",
    "kategorie": "Alltag",
    "kategorieSlug": "alltag",
    "keywords": [
      "kaffee kosten rechner",
      "kaffee kosten pro tag",
      "kaffee kosten pro monat",
      "kaffee kosten pro jahr",
      "kaffee ausgaben berechnen",
      "kaffee sparen",
      "filterkaffee kosten",
      "kapselkaffee kosten",
      "café kosten",
      "starbucks kosten"
    ],
    "icon": "☕"
  },
  {
    "slug": "lieferservice-rechner",
    "titel": "Lieferservice-Rechner",
    "beschreibung": "Berechnen Sie Ihre Lieferservice-Kosten pro Monat und Jahr — mit Vergleich zum Selberkochen und Spartipps.",
    "kategorie": "Alltag",
    "kategorieSlug": "alltag",
    "keywords": [
      "lieferservice rechner",
      "lieferservice kosten",
      "lieferdienst kosten",
      "bestellen kosten",
      "lieferando kosten",
      "selber kochen sparen",
      "essenslieferung kosten",
      "liefergebühr rechner",
      "lieferdienst vs selber kochen",
      "essen bestellen kosten"
    ],
    "icon": "🛵"
  },
  {
    "slug": "abo-rechner",
    "titel": "Abo-Rechner",
    "beschreibung": "Alle Abos auf einen Blick: Berechnen Sie Ihre monatlichen und jährlichen Abo-Kosten — mit Ranking und Spartipps.",
    "kategorie": "Alltag",
    "kategorieSlug": "alltag",
    "keywords": [
      "abo rechner",
      "abo kosten",
      "abonnement kosten",
      "monatliche abos",
      "streaming abos kosten",
      "abo übersicht",
      "abo kündigen sparen",
      "fixkosten rechner",
      "abos berechnen",
      "abo vergleich"
    ],
    "icon": "🔄"
  },
  {
    "slug": "handykosten-rechner",
    "titel": "Handykosten-Rechner",
    "beschreibung": "Handykosten berechnen: Effektive Monatskosten, Jahreskosten und Kostenaufschlüsselung für Ihren Mobilfunkvertrag.",
    "kategorie": "Alltag",
    "kategorieSlug": "alltag",
    "keywords": [
      "handykosten rechner",
      "handykosten berechnen",
      "handyvertrag kosten",
      "mobilfunk kosten",
      "handykosten pro monat",
      "effektive handykosten",
      "handytarif vergleich",
      "monatliche handykosten",
      "handyvertrag vergleich",
      "smartphone kosten"
    ],
    "icon": "📱"
  },
  {
    "slug": "umzugskosten-rechner",
    "titel": "Umzugskosten-Rechner",
    "beschreibung": "Umzugskosten berechnen: Geschätzte Kosten für Umzugsfirma, Transporter, Verpackung und Nebenkosten.",
    "kategorie": "Alltag",
    "kategorieSlug": "alltag",
    "keywords": [
      "umzugskosten rechner",
      "umzugskosten berechnen",
      "was kostet ein umzug",
      "umzugsfirma kosten",
      "umzug kosten schätzen",
      "umzugskosten deutschland",
      "umzug selbst organisiert kosten",
      "transporter umzug kosten",
      "umzugskosten steuer absetzen",
      "umzug checkliste"
    ],
    "icon": "📦"
  },
  {
    "slug": "trinkgeld-rechner",
    "titel": "Trinkgeld-Rechner",
    "beschreibung": "Trinkgeld berechnen: Prozent oder fester Betrag, Rechnung teilen, auf glatten Betrag aufrunden.",
    "kategorie": "Alltag",
    "kategorieSlug": "alltag",
    "keywords": [
      "trinkgeld rechner",
      "trinkgeld berechnen",
      "trinkgeld prozent",
      "rechnung teilen rechner",
      "wie viel trinkgeld",
      "trinkgeld deutschland",
      "trinkgeld restaurant",
      "tip calculator deutsch",
      "trinkgeld aufrunden",
      "trinkgeld knigge"
    ],
    "icon": "💰"
  },
  {
    "slug": "geburtstag-rechner",
    "titel": "Geburtstags-Rechner",
    "beschreibung": "Geburtstag berechnen: Alter in Tagen, Stunden und Minuten, Wochentag der Geburt, Sternzeichen und nächster runder Geburtstag.",
    "kategorie": "Alltag",
    "kategorieSlug": "alltag",
    "keywords": [
      "geburtstag rechner",
      "alter in tagen",
      "alter in stunden",
      "wochentag geburt",
      "wie alt bin ich in tagen",
      "sternzeichen berechnen",
      "nächster runder geburtstag",
      "geburtstag berechnen",
      "alter in minuten",
      "tage seit geburt"
    ],
    "icon": "🎂"
  },
  {
    "slug": "skontorechner",
    "titel": "Skontorechner",
    "beschreibung": "Skonto berechnen: Ersparnis durch Skonto und effektiven Jahreszins — lohnt sich die frühzeitige Zahlung?",
    "kategorie": "Alltag",
    "kategorieSlug": "alltag",
    "keywords": [
      "skontorechner",
      "skonto berechnen",
      "skonto ersparnis",
      "effektiver jahreszins skonto",
      "skonto 2 prozent",
      "skonto ziehen",
      "skonto formel",
      "zahlungsziel skonto"
    ],
    "icon": "💸"
  },
  {
    "slug": "uhrzeitrechner",
    "titel": "Uhrzeitrechner",
    "beschreibung": "Uhrzeiten berechnen: Zeitdifferenz, Stunden addieren/subtrahieren und Zeitzonen umrechnen.",
    "kategorie": "Alltag",
    "kategorieSlug": "alltag",
    "keywords": [
      "uhrzeitrechner",
      "zeitdifferenz berechnen",
      "stunden addieren",
      "zeitzonen rechner",
      "dezimalstunden",
      "zeitverschiebung berechnen",
      "mez est umrechnen"
    ],
    "icon": "🕐"
  },
  {
    "slug": "hundejahre-rechner",
    "titel": "Hundejahre-Rechner",
    "beschreibung": "Hundejahre in Menschenjahre umrechnen — differenziert nach Größe und Rasse. Vergessen Sie die alte 1:7-Formel!",
    "kategorie": "Alltag",
    "kategorieSlug": "alltag",
    "keywords": [
      "hundejahre rechner",
      "hundealter menschenjahre",
      "hundejahre umrechnen",
      "wie alt ist mein hund",
      "hundealter rasse",
      "hunde lebenserwartung"
    ],
    "icon": "🐕"
  },
  {
    "slug": "waehrungsrechner",
    "titel": "Währungsrechner",
    "beschreibung": "Beträge zwischen 29 Währungen umrechnen — mit statischen Referenzkursen vom 14.04.2026.",
    "kategorie": "Alltag",
    "kategorieSlug": "alltag",
    "keywords": [
      "währungsrechner",
      "wechselkurs rechner",
      "euro dollar umrechnen",
      "euro franken umrechnen",
      "währung umrechnen",
      "devisenrechner",
      "wechselkurse"
    ],
    "icon": "💱"
  },
  {
    "slug": "schuhgroessen-rechner",
    "titel": "Schuhgrößen-Umrechner",
    "beschreibung": "Schuhgrößen umrechnen: EU, US, UK und cm — für Damen, Herren und Kinder mit vollständiger Tabelle.",
    "kategorie": "Alltag",
    "kategorieSlug": "alltag",
    "keywords": [
      "schuhgrößen umrechner",
      "schuhgröße umrechnen",
      "eu us uk schuhgröße",
      "schuhgröße cm",
      "fußlänge schuhgröße",
      "damen schuhgröße us",
      "herren schuhgröße uk",
      "kinderschuhgröße",
      "schuhgröße tabelle"
    ],
    "icon": "👟"
  },
  {
    "slug": "kleidergroessen-rechner",
    "titel": "Kleidergrößen-Umrechner",
    "beschreibung": "Kleidergrößen umrechnen: DE, EU, US, UK und IT für Damen und Herren mit Maßtabelle und Empfehlung.",
    "kategorie": "Alltag",
    "kategorieSlug": "alltag",
    "keywords": [
      "kleidergrößen umrechnen",
      "konfektionsgrößen",
      "damen größe",
      "herren größe",
      "us größe in deutsche",
      "uk größe",
      "italienische größe",
      "maßtabelle kleidung"
    ],
    "icon": "👕"
  },
  {
    "slug": "reisekosten-rechner",
    "titel": "Reisekosten-Rechner",
    "beschreibung": "Reisekosten berechnen: Gesamtbudget für Anreise, Unterkunft, Essen und Aktivitäten planen.",
    "kategorie": "Alltag & Leben",
    "kategorieSlug": "alltag",
    "keywords": [
      "reisekosten rechner",
      "urlaub budget",
      "reisebudget planen",
      "urlaubskosten",
      "reise kosten berechnen",
      "urlaub kosten pro tag"
    ],
    "icon": "✈️"
  },
  {
    "slug": "zeitwert-rechner",
    "titel": "Zeitwert-Rechner",
    "beschreibung": "Zeitwert gebrauchter Gegenstände berechnen: Restwert für Versicherung, Verkauf oder Schadensersatz.",
    "kategorie": "Alltag & Leben",
    "kategorieSlug": "alltag",
    "keywords": [
      "zeitwert rechner",
      "restwert berechnen",
      "wertverlust",
      "zeitwert möbel",
      "zeitwert elektronik",
      "lineare abschreibung",
      "gebrauchtwert"
    ],
    "icon": "📦"
  },
  {
    "slug": "budget-rechner",
    "titel": "Budget-Rechner",
    "beschreibung": "Haushaltsbudget berechnen: Einnahmen vs. Ausgaben aufschlüsseln, Sparpotenzial identifizieren und 50/30/20-Regel prüfen.",
    "kategorie": "Alltag",
    "kategorieSlug": "alltag",
    "keywords": [
      "budget rechner",
      "haushaltsbuch",
      "50 30 20 regel",
      "haushaltsbudget",
      "ausgaben berechnen",
      "sparquote",
      "budgetplaner",
      "haushaltsbuch rechner",
      "ausgaben aufschlüsseln"
    ],
    "icon": "💰"
  },
  {
    "slug": "brutto-netto-rechner",
    "titel": "Brutto-Netto-Rechner",
    "beschreibung": "Nettogehalt berechnen: Mit Steuerklasse, Bundesland, Kirchensteuer, KV und allen Sozialabgaben.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "brutto netto rechner",
      "brutto netto rechner 2026",
      "gehaltsrechner",
      "nettogehalt berechnen",
      "lohnrechner",
      "netto brutto",
      "steuerklasse",
      "gehaltsrechner 2026",
      "nettolohn berechnen",
      "was bleibt vom brutto"
    ],
    "icon": "💶"
  },
  {
    "slug": "mwst-rechner",
    "titel": "MwSt-Rechner",
    "beschreibung": "Mehrwertsteuer berechnen: Brutto ↔ Netto, MwSt herausrechnen, Multi-Rechner für Rechnungen.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "mwst rechner",
      "mehrwertsteuer rechner",
      "netto brutto rechner",
      "brutto netto",
      "umsatzsteuer rechner",
      "mwst herausrechnen",
      "mehrwertsteuer berechnen",
      "19 prozent mwst",
      "mwst aus brutto berechnen",
      "netto berechnen"
    ],
    "icon": "🧾"
  },
  {
    "slug": "zinsrechner",
    "titel": "Zinsrechner",
    "beschreibung": "Zinsen und Zinseszins berechnen: Mit Sparplan, Jahr-für-Jahr-Tabelle und Zinseszins-Vergleich.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "zinsrechner",
      "zinseszins rechner",
      "zinsen berechnen",
      "sparplan rechner",
      "zinseszinsrechner",
      "kapital berechnen"
    ],
    "icon": "📈"
  },
  {
    "slug": "elterngeld-rechner",
    "titel": "Elterngeld-Rechner",
    "beschreibung": "Elterngeld 2026 berechnen: Basiselterngeld & ElterngeldPlus mit Geschwisterbonus und Mehrlingszuschlag.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "elterngeld rechner",
      "elterngeld berechnen",
      "elterngeld 2026",
      "basiselterngeld",
      "elterngeld plus",
      "elterngeldrechner",
      "geschwisterbonus"
    ],
    "icon": "👶"
  },
  {
    "slug": "buergergeld-rechner",
    "titel": "Bürgergeld-Rechner",
    "beschreibung": "Bürgergeld 2026 berechnen: Aktuelle Regelsätze mit Einkommensanrechnung und Vermögensprüfung.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "bürgergeld rechner",
      "bürgergeld 2026",
      "bürgergeld berechnen",
      "regelsatz 2026",
      "bürgergeld anspruch",
      "hartz 4 rechner",
      "jobcenter"
    ],
    "icon": "🏛️"
  },
  {
    "slug": "stundenlohn-rechner",
    "titel": "Stundenlohnrechner",
    "beschreibung": "Stundenlohn aus Monatsgehalt berechnen oder umgekehrt — mit Mindestlohn-Vergleich und effektivem Stundenlohn.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "stundenlohn rechner",
      "stundenlohn berechnen",
      "gehalt in stundenlohn",
      "monatsgehalt berechnen",
      "stundenlohnrechner",
      "mindestlohn 2026"
    ],
    "icon": "🕐"
  },
  {
    "slug": "sparrechner",
    "titel": "Sparrechner",
    "beschreibung": "Sparplan berechnen mit Zinseszins: Monatliche Sparrate, Dynamik und Jahr-für-Jahr-Entwicklung.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "sparrechner",
      "sparplan rechner",
      "sparplan berechnen",
      "zinseszins rechner",
      "etf sparplan rechner",
      "sparrate berechnen",
      "vermögensaufbau"
    ],
    "icon": "🐖"
  },
  {
    "slug": "inflationsrechner",
    "titel": "Inflationsrechner",
    "beschreibung": "Kaufkraftverlust und Preisanstieg durch Inflation berechnen — mit Jahr-für-Jahr-Tabelle.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "inflationsrechner",
      "inflation berechnen",
      "kaufkraftverlust",
      "preisanstieg berechnen",
      "inflationsrate",
      "kaufkraft rechner",
      "geldentwertung"
    ],
    "icon": "📉"
  },
  {
    "slug": "gehaltsvergleich",
    "titel": "Gehaltsvergleich",
    "beschreibung": "Vergleichen Sie Ihr Gehalt mit dem Durchschnitt Ihrer Berufsgruppe, Ihres Bundeslandes und Ihrer Altersgruppe.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "gehaltsvergleich",
      "gehalt vergleichen",
      "durchschnittsgehalt",
      "gehaltscheck",
      "verdiene ich genug",
      "gehaltsrechner",
      "gehalt deutschland",
      "median gehalt",
      "gehalt berufsgruppe",
      "gehalt bundesland"
    ],
    "icon": "💵"
  },
  {
    "slug": "wahrer-stundenlohn",
    "titel": "Wahrer Stundenlohn Rechner",
    "beschreibung": "Was verdienen Sie wirklich pro Stunde? Berechnen Sie Ihren wahren Stundenlohn inklusive Pendelzeit, Fahrtkosten und Überstunden.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "wahrer stundenlohn",
      "stundenlohn berechnen",
      "was verdiene ich wirklich",
      "netto stundenlohn",
      "stundenlohn mit pendelzeit",
      "echter stundenlohn",
      "stundenlohn rechner",
      "versteckte arbeitskosten",
      "realer stundenlohn",
      "pendelzeit kosten"
    ],
    "icon": "🔍"
  },
  {
    "slug": "steuererstattung-rechner",
    "titel": "Steuererstattungs-Rechner",
    "beschreibung": "Steuererstattung schätzen: Mögliche Rückzahlung vom Finanzamt anhand Ihrer Ausgaben berechnen.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "steuererstattung rechner",
      "steuererstattung berechnen",
      "steuererklärung erstattung",
      "steuer zurück bekommen",
      "werbungskosten absetzen",
      "pendlerpauschale steuer",
      "homeoffice pauschale",
      "steuerersparnis berechnen",
      "steuerrückzahlung",
      "lohnsteuer erstattung"
    ],
    "icon": "💸"
  },
  {
    "slug": "kreditrechner",
    "titel": "Kreditrechner",
    "beschreibung": "Kreditrate, Gesamtkosten und Tilgungsplan berechnen — für Ratenkredite, Autokredite und Konsumkredite.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "kreditrechner",
      "kreditrate berechnen",
      "tilgungsrechner",
      "kredit berechnen",
      "annuitätenrechner",
      "ratenkreditrechner"
    ],
    "icon": "🏦"
  },
  {
    "slug": "etf-sparplanrechner",
    "titel": "ETF-Sparplanrechner",
    "beschreibung": "ETF-Sparplan berechnen: Endkapital, Rendite und Vermögensentwicklung für Ihren monatlichen Sparplan simulieren.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "etf sparplanrechner",
      "etf sparplan berechnen",
      "sparplan rendite rechner",
      "etf rechner",
      "sparplan rechner",
      "etf rendite berechnen",
      "vermögensaufbau rechner",
      "msci world rechner"
    ],
    "icon": "📈"
  },
  {
    "slug": "rentenrechner",
    "titel": "Rentenrechner",
    "beschreibung": "Gesetzliche Rente schätzen: Voraussichtliche Monatsrente, Rentenpunkte und Rentenlücke berechnen.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "rentenrechner",
      "rente berechnen",
      "rentenpunkte berechnen",
      "rentenlücke rechner",
      "gesetzliche rente rechner",
      "rente mit 63",
      "monatsrente berechnen",
      "rentenanspruch berechnen",
      "netto rente rechner",
      "altersvorsorge rechner"
    ],
    "icon": "👴"
  },
  {
    "slug": "splitting-rechner",
    "titel": "Splitting-Rechner",
    "beschreibung": "Ehegattensplitting berechnen: Steuervorteil durch Zusammenveranlagung im Vergleich zur Einzelveranlagung.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "splitting rechner",
      "ehegattensplitting rechner",
      "ehegattensplitting berechnen",
      "steuervorteil ehe",
      "zusammenveranlagung rechner",
      "steuerklassen ehepaar",
      "splittingtarif",
      "steuerklasse 3 5 rechner",
      "splitting vorteil",
      "steuererklärung ehepaar"
    ],
    "icon": "💍"
  },
  {
    "slug": "wohngeld-rechner",
    "titel": "Wohngeld-Rechner",
    "beschreibung": "Wohngeld berechnen: Prüfen Sie Ihren Anspruch und die voraussichtliche Höhe des Wohngelds nach dem Wohngeld-Plus-Gesetz 2026.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "wohngeld rechner",
      "wohngeld berechnen",
      "wohngeld 2026",
      "wohngeld anspruch",
      "wohngeld höhe",
      "wohngeld plus",
      "wohngeld mietstufe",
      "wohngeldantrag",
      "mietzuschuss berechnen",
      "wohngeld einkommensgrenze"
    ],
    "icon": "🏠"
  },
  {
    "slug": "bafoeg-rechner",
    "titel": "BAföG-Rechner",
    "beschreibung": "BAföG berechnen: Anspruch und voraussichtliche Höhe der Ausbildungsförderung für Studierende und Schüler.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "bafög rechner",
      "bafög berechnen",
      "bafög 2026",
      "bafög anspruch",
      "bafög höhe",
      "bafög höchstsatz",
      "bafög elterneinkommen",
      "bafög rückzahlung",
      "studenten bafög",
      "schüler bafög"
    ],
    "icon": "🎓"
  },
  {
    "slug": "kindergeld-rechner",
    "titel": "Kindergeld-Rechner",
    "beschreibung": "Kindergeld 2026 berechnen und Günstigerprüfung: Kindergeld oder Kinderfreibetrag — was lohnt sich für Ihr Einkommen?",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "kindergeld rechner",
      "kindergeld 2026",
      "kindergeld berechnen",
      "kinderfreibetrag",
      "günstigerprüfung",
      "kindergeld höhe",
      "255 euro kindergeld",
      "kinderfreibetrag 2026",
      "kindergeld steuer",
      "familienkasse"
    ],
    "icon": "👶"
  },
  {
    "slug": "pflegegeld-rechner",
    "titel": "Pflegegeld-Rechner",
    "beschreibung": "Pflegegeld berechnen: Leistungen der Pflegeversicherung nach Pflegegrad — Pflegegeld, Pflegesachleistung und Kombinationsleistung.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "pflegegeld rechner",
      "pflegegeld 2026",
      "pflegegrad",
      "pflegesachleistung",
      "kombinationsleistung",
      "pflegeversicherung",
      "pflegeheim eigenanteil",
      "entlastungsbetrag",
      "verhinderungspflege",
      "kurzzeitpflege"
    ],
    "icon": "🏥"
  },
  {
    "slug": "erbschaftsteuer-rechner",
    "titel": "Erbschaftsteuer-Rechner",
    "beschreibung": "Erbschaftsteuer und Schenkungsteuer berechnen: Freibetrag, Steuersatz und Steuerlast nach Verwandtschaftsgrad.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "erbschaftsteuer rechner",
      "erbschaftssteuer 2026",
      "schenkungsteuer rechner",
      "erbschaftssteuer freibetrag",
      "freibetrag kind",
      "freibetrag ehepartner",
      "erbschaftsteuer steuerklasse",
      "erbschaft berechnen",
      "10 jahre schenkung",
      "familienheim"
    ],
    "icon": "🏛️"
  },
  {
    "slug": "minijob-rechner",
    "titel": "Minijob-Rechner",
    "beschreibung": "Minijob-Abgaben berechnen: Verdienst, Abgaben für Arbeitgeber und Arbeitnehmer sowie Übergang zum Midijob.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "minijob rechner",
      "minijob 603 euro",
      "minijob grenze 2026",
      "minijob abgaben arbeitgeber",
      "minijob netto",
      "520 euro job",
      "538 euro job",
      "midijob rechner",
      "minijob rentenversicherung",
      "pauschalabgaben minijob"
    ],
    "icon": "💶"
  },
  {
    "slug": "gehaltserhoehung-rechner",
    "titel": "Gehaltserhöhung-Rechner",
    "beschreibung": "Gehaltserhöhung berechnen: Wie viel Netto bleibt von Ihrer Brutto-Erhöhung — mit Steuer- und Abgabeneffekt.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "gehaltserhöhung rechner",
      "gehaltserhöhung netto",
      "brutto erhöhung netto",
      "grenzbelastung gehalt",
      "wie viel netto bleibt",
      "kalte progression",
      "reallohnerhöhung",
      "gehaltssprung steuer",
      "gehaltserhöhung berechnen",
      "gehaltserhöhung wie viel netto"
    ],
    "icon": "📈"
  },
  {
    "slug": "krankengeld-rechner",
    "titel": "Krankengeld-Rechner",
    "beschreibung": "Krankengeld berechnen: Tägliches und monatliches Krankengeld bei Arbeitsunfähigkeit — mit Netto-Vergleich.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "krankengeld rechner",
      "krankengeld berechnen",
      "krankengeld hoehe",
      "krankengeld 70 prozent",
      "krankengeld netto",
      "krankengeld dauer",
      "lohnfortzahlung",
      "progressionsvorbehalt krankengeld"
    ],
    "icon": "🏥"
  },
  {
    "slug": "gmbh-geschaeftsfuehrer-rechner",
    "titel": "GmbH-Geschäftsführer-Rechner",
    "beschreibung": "Netto-Gehalt des GmbH-Geschäftsführers berechnen: Mit Sozialversicherungsfreiheit, Firmenwagen, PKV und Einkommensteuer.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "gmbh geschäftsführer rechner",
      "ggf gehalt netto",
      "gesellschafter geschäftsführer",
      "geschäftsführer brutto netto",
      "gmbh gf sv frei",
      "firmenwagen 1 prozent regelung",
      "gmbh gehalt 2026"
    ],
    "icon": "🏢"
  },
  {
    "slug": "hochrechner",
    "titel": "Hochrechner (Gehalt)",
    "beschreibung": "Rechnen Sie Stunden-, Tages-, Wochen-, Monats- oder Jahreslohn ineinander um — inkl. Mindestlohn-Vergleich 2026.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "hochrechner",
      "gehalt hochrechnen",
      "stundenlohn monatslohn umrechnen",
      "jahreslohn berechnen",
      "mindestlohn 2026",
      "bruttogehalt hochrechnen"
    ],
    "icon": "📈"
  },
  {
    "slug": "midijob-rechner",
    "titel": "Midijob-Rechner",
    "beschreibung": "Midijob-Abgaben berechnen: Reduzierte Sozialversicherungsbeiträge im Übergangsbereich von 603,01 bis 2.000 Euro.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "midijob rechner",
      "übergangsbereich",
      "midijob 2026",
      "midijob netto",
      "gleitzone",
      "beitragspflichtige einnahme",
      "faktor f"
    ],
    "icon": "💶"
  },
  {
    "slug": "firmenwagenrechner",
    "titel": "Firmenwagenrechner",
    "beschreibung": "Firmenwagen-Steuer berechnen: Geldwerter Vorteil nach 1%-Regel für Verbrenner, Hybrid und Elektroauto.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "firmenwagenrechner",
      "1 prozent regel",
      "geldwerter vorteil",
      "dienstwagen rechner",
      "e-auto firmenwagen",
      "0 25 prozent regel",
      "firmenwagen steuer"
    ],
    "icon": "🚗"
  },
  {
    "slug": "witwenrente-rechner",
    "titel": "Witwenrente-Rechner",
    "beschreibung": "Witwenrente berechnen: Große und kleine Witwenrente, Einkommensanrechnung und Rentenanspruch.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "witwenrente rechner",
      "witwenrente berechnen",
      "witwerrente",
      "große witwenrente",
      "kleine witwenrente",
      "witwenrente einkommensanrechnung",
      "witwenrente freibetrag",
      "sterbevierteljahr",
      "witwenrente höhe"
    ],
    "icon": "🕊️"
  },
  {
    "slug": "kurzarbeitergeld-rechner",
    "titel": "Kurzarbeitergeld-Rechner",
    "beschreibung": "Kurzarbeitergeld berechnen: KuG-Höhe basierend auf Ihrem Gehalt und der Arbeitszeitreduzierung.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "kurzarbeitergeld rechner",
      "kug rechner",
      "kurzarbeitergeld berechnen",
      "kurzarbeit rechner",
      "nettoentgeltdifferenz",
      "kug höhe",
      "kurzarbeit 60 prozent",
      "kurzarbeit 67 prozent"
    ],
    "icon": "⏱️"
  },
  {
    "slug": "riester-rechner",
    "titel": "Riester-Rechner",
    "beschreibung": "Riester-Rente berechnen: Zulage, Eigenbeitrag, Steuerersparnis und ob sich Riestern für Sie lohnt.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "riester rechner",
      "riester rente berechnen",
      "riester zulage",
      "riester eigenbeitrag",
      "riester kinderzulage",
      "riester steuerersparnis",
      "riester lohnt sich",
      "günstigerprüfung riester"
    ],
    "icon": "📊"
  },
  {
    "slug": "nettolohn-optimierer",
    "titel": "Nettolohn-Optimierer",
    "beschreibung": "Nettolohn optimieren: Vergleich Gehaltserhöhung vs. steuerfreie Sachbezüge — was bringt mehr Netto?",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "nettolohn optimieren",
      "sachbezüge",
      "steuerfreie gehaltsextras",
      "gehaltserhöhung vs sachbezug",
      "jobticket steuerfrei",
      "essenszuschuss",
      "betriebliche altersvorsorge",
      "50 euro sachbezug",
      "nettolohn maximieren"
    ],
    "icon": "💡"
  },
  {
    "slug": "kapitalertragsteuer-rechner",
    "titel": "Kapitalertragsteuer-Rechner",
    "beschreibung": "Abgeltungssteuer auf Zinsen, Dividenden und Kursgewinne berechnen — inkl. Sparerpauschbetrag, Teilfreistellung und Kirchensteuer.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "kapitalertragsteuer rechner",
      "abgeltungssteuer berechnen",
      "kapitalertragsteuer 2026",
      "sparerpauschbetrag",
      "teilfreistellung etf",
      "dividenden steuer",
      "zinsen steuer",
      "kirchensteuer kapitalerträge",
      "günstigerprüfung",
      "anlage kap"
    ],
    "icon": "📈"
  },
  {
    "slug": "afa-rechner",
    "titel": "AfA-Rechner",
    "beschreibung": "Abschreibung berechnen: Lineare und degressive AfA für Anlagegüter, Immobilien und GWG mit AfA-Plan und Rechenweg.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "afa rechner",
      "abschreibung berechnen",
      "afa linear",
      "afa degressiv",
      "gwg abschreibung",
      "afa tabelle",
      "nutzungsdauer",
      "anlagevermögen abschreibung",
      "restbuchwert berechnen",
      "afa pro rata temporis"
    ],
    "icon": "📉"
  },
  {
    "slug": "betriebskosten-rechner",
    "titel": "Betriebskosten-Rechner",
    "beschreibung": "Monatliche Betriebskosten für Selbstständige und Gewerbe kalkulieren — mit Break-Even-Analyse.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "betriebskosten rechner",
      "betriebskosten berechnen",
      "kosten selbstständige",
      "fixkosten variable kosten",
      "break even analyse",
      "unternehmerlohn berechnen",
      "stundensatz kalkulation",
      "betriebsausgaben"
    ],
    "icon": "💼"
  },
  {
    "slug": "mwst-rueckerstattung-rechner",
    "titel": "MwSt-Rückerstattungs-Rechner",
    "beschreibung": "Tax-Free-Shopping berechnen: MwSt-Erstattung für Nicht-EU-Touristen beim Einkauf in Deutschland.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "mwst rückerstattung rechner",
      "tax free shopping deutschland",
      "mehrwertsteuer erstattung touristen",
      "tax refund germany",
      "global blue rechner",
      "umsatzsteuer rückerstattung",
      "tax free rechner"
    ],
    "icon": "🧾"
  },
  {
    "slug": "steuerprogression-rechner",
    "titel": "Steuerprogression-Rechner",
    "beschreibung": "Steuerprogression visualisieren: Durchschnitts- und Grenzsteuersatz für jedes Einkommen berechnen.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "steuerprogression",
      "grenzsteuersatz rechner",
      "durchschnittssteuersatz",
      "einkommensteuer tarif",
      "steuerprogression rechner",
      "steuersatz berechnen",
      "progressiver steuertarif",
      "einkommensteuer kurve",
      "steuertarif 2026"
    ],
    "icon": "📊"
  },
  {
    "slug": "spenden-rechner",
    "titel": "Spenden-Rechner",
    "beschreibung": "Steuerersparnis durch Spenden berechnen: Wie viel bekommen Sie von Ihrer Spende über die Steuererklärung zurück?",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "spenden rechner",
      "spenden steuerersparnis",
      "spenden absetzen",
      "spendenquittung",
      "sonderausgabenabzug",
      "spenden steuer",
      "spenden von der steuer absetzen",
      "steuerersparnis spende",
      "spenden steuerlich absetzbar"
    ],
    "icon": "🎁"
  },
  {
    "slug": "nebenjob-rechner",
    "titel": "Nebenjob-Rechner",
    "beschreibung": "Nebenjob-Steuer berechnen: Auswirkung eines Nebenjobs auf Steuern und Sozialversicherung neben dem Hauptjob.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "nebenjob rechner",
      "nebenjob steuer",
      "nebenjob steuern",
      "minijob neben hauptjob",
      "steuerklasse 6",
      "nebenverdienst steuer",
      "nebenjob netto",
      "zweiter job steuer",
      "nebeneinkünfte steuer"
    ],
    "icon": "💼"
  },
  {
    "slug": "schenkungssteuer-rechner",
    "titel": "Schenkungssteuer-Rechner",
    "beschreibung": "Schenkungssteuer berechnen: Freibeträge, Steuerklassen und 10-Jahres-Regel bei Schenkungen an Verwandte.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "schenkungssteuer rechner",
      "schenkungssteuer berechnen",
      "schenkungssteuer freibetrag",
      "schenkung freibetrag",
      "schenkungssteuer steuerklasse",
      "freibetrag schenkung kind",
      "schenkung 10 jahre",
      "kettenschenkung",
      "schenkungssteuer tabelle"
    ],
    "icon": "🎁"
  },
  {
    "slug": "gewerbesteuer-rechner",
    "titel": "Gewerbesteuer-Rechner",
    "beschreibung": "Gewerbesteuer berechnen: Hebesatz, Steuermessbetrag, Freibetrag und ESt-Anrechnung für Gewerbetreibende.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "gewerbesteuer rechner",
      "gewerbesteuer berechnen",
      "gewerbesteuer hebesatz",
      "gewerbesteuer freibetrag",
      "steuermessbetrag",
      "gewerbesteuer anrechnung",
      "gewerbesteuer einzelunternehmen",
      "gewerbesteuer gmbh",
      "gewerbesteuer 2026"
    ],
    "icon": "🏭"
  },
  {
    "slug": "einkommensteuer-rechner",
    "titel": "Einkommensteuer-Rechner",
    "beschreibung": "Einkommensteuer berechnen: Grundtabelle, Splitting, Soli, Kirchensteuer und Grenzsteuersatz nach § 32a EStG.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "einkommensteuer rechner",
      "einkommensteuer berechnen",
      "est rechner",
      "32a estg",
      "einkommensteuer 2026",
      "einkommensteuer tabelle",
      "grenzsteuersatz rechner",
      "durchschnittssteuersatz",
      "einkommensteuer splitting",
      "grundtabelle"
    ],
    "icon": "📋"
  },
  {
    "slug": "steuerklassen-vergleich-rechner",
    "titel": "Steuerklassen-Vergleich-Rechner",
    "beschreibung": "Steuerklassen-Kombinationen vergleichen: III/V, V/III und IV/IV mit Faktor — welche Wahl bringt das höchste monatliche Netto?",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "steuerklassen vergleich",
      "steuerklasse 3 5",
      "steuerklasse 4 4 faktor",
      "steuerklasse ehepaar",
      "faktorverfahren",
      "steuerklasse wechseln",
      "steuerklasse optimieren",
      "beste steuerklasse ehepaar",
      "iii v oder iv iv"
    ],
    "icon": "⚖️"
  },
  {
    "slug": "pfaendungsrechner",
    "titel": "Pfändungsrechner",
    "beschreibung": "Pfändungsfreies Einkommen berechnen: Freibetrag nach § 850c ZPO, Erhöhung bei Unterhaltspflichten, P-Konto.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "pfändungsrechner",
      "pfändungsfreibetrag",
      "pfändungstabelle 2026",
      "850c zpo",
      "pfändungsfreigrenze",
      "p-konto freibetrag",
      "lohnpfändung",
      "unterhaltspflicht pfändung",
      "gehaltspfändung rechner"
    ],
    "icon": "⚖️"
  },
  {
    "slug": "lohnsteuer-rechner",
    "titel": "Lohnsteuer-Rechner",
    "beschreibung": "Lohnsteuer berechnen: Steuerklasse I–VI, Bundesland, Kirchensteuer, Kinderfreibeträge — monatlich oder jährlich.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "lohnsteuer rechner",
      "lohnsteuer berechnen",
      "lohnsteuer 2026",
      "lohnsteuer steuerklasse",
      "lohnsteuer tabelle 2026",
      "pap 2026",
      "lohnsteuer monatlich",
      "lohnsteuer jahrestabelle",
      "lohnsteuer rechner brutto",
      "lohnsteuer klasse 1"
    ],
    "icon": "💷"
  },
  {
    "slug": "bmi-rechner",
    "titel": "BMI-Rechner",
    "beschreibung": "Body Mass Index berechnen: Mit WHO-Einordnung, farbiger Skala und optimalem BMI-Bereich für Ihr Alter.",
    "kategorie": "Gesundheit",
    "kategorieSlug": "gesundheit",
    "keywords": [
      "bmi rechner",
      "bmi berechnen",
      "body mass index",
      "bmi tabelle",
      "bmi formel",
      "idealgewicht"
    ],
    "icon": "❤️"
  },
  {
    "slug": "raucher-rechner",
    "titel": "Raucher-Rechner",
    "beschreibung": "Berechnen Sie, wie viel Geld Sie fürs Rauchen ausgeben — und was Sie sich stattdessen leisten könnten.",
    "kategorie": "Gesundheit",
    "kategorieSlug": "gesundheit",
    "keywords": [
      "raucher rechner",
      "kosten rauchen",
      "zigaretten kosten",
      "rauchen kosten pro monat",
      "rauchen kosten pro jahr",
      "rauchen aufhören sparen",
      "zigarettenpreis rechner",
      "was kostet rauchen",
      "raucher kosten",
      "rauchfrei rechner"
    ],
    "icon": "🚬"
  },
  {
    "slug": "schlaf-rechner",
    "titel": "Schlafrechner",
    "beschreibung": "Optimale Schlafenszeit berechnen: Wann ins Bett gehen, um ausgeruht aufzuwachen? Basierend auf 90-Minuten-Schlafzyklen.",
    "kategorie": "Gesundheit",
    "kategorieSlug": "gesundheit",
    "keywords": [
      "schlafrechner",
      "optimale schlafenszeit",
      "schlafzyklen berechnen",
      "wann ins bett gehen",
      "schlaf rechner",
      "schlafphasen",
      "rem schlaf",
      "wie viel schlaf brauche ich",
      "schlafzyklen",
      "aufwachzeit berechnen"
    ],
    "icon": "😴"
  },
  {
    "slug": "kalorienrechner",
    "titel": "Kalorienrechner",
    "beschreibung": "Täglichen Kalorienbedarf berechnen: Grundumsatz und Gesamtumsatz basierend auf der Mifflin-St Jeor-Formel.",
    "kategorie": "Gesundheit",
    "kategorieSlug": "gesundheit",
    "keywords": [
      "kalorienrechner",
      "kalorienbedarf berechnen",
      "grundumsatz berechnen",
      "gesamtumsatz",
      "mifflin st jeor",
      "kalorienverbrauch",
      "kcal rechner",
      "täglicher kalorienbedarf"
    ],
    "icon": "🍎"
  },
  {
    "slug": "geburtstermin-rechner",
    "titel": "Geburtstermin-Rechner",
    "beschreibung": "Geburtstermin berechnen: Nach der Naegele-Regel mit drei Methoden — letzte Periode, Empfängnisdatum oder Ultraschall.",
    "kategorie": "Gesundheit",
    "kategorieSlug": "gesundheit",
    "keywords": [
      "geburtstermin berechnen",
      "geburtsterminrechner",
      "entbindungstermin berechnen",
      "ssw berechnen",
      "schwangerschaftswoche berechnen",
      "naegele regel",
      "geburtstermin rechner",
      "et berechnen"
    ],
    "icon": "🤰"
  },
  {
    "slug": "idealgewicht-rechner",
    "titel": "Idealgewicht-Rechner",
    "beschreibung": "Idealgewicht berechnen nach verschiedenen Formeln: Broca, Creff und BMI-basiert — mit persönlicher Idealgewicht-Spanne.",
    "kategorie": "Gesundheit",
    "kategorieSlug": "gesundheit",
    "keywords": [
      "idealgewicht berechnen",
      "idealgewicht rechner",
      "broca formel",
      "creff formel",
      "normalgewicht berechnen",
      "idealgewicht frau",
      "idealgewicht mann",
      "idealgewicht nach alter"
    ],
    "icon": "⚖️"
  },
  {
    "slug": "wasserbedarf-rechner",
    "titel": "Wasserbedarf-Rechner",
    "beschreibung": "Täglichen Wasserbedarf berechnen: Empfohlene Trinkmenge basierend auf Gewicht, Aktivität und individuellen Faktoren.",
    "kategorie": "Gesundheit",
    "kategorieSlug": "gesundheit",
    "keywords": [
      "wasserbedarf rechner",
      "trinkmenge berechnen",
      "wie viel wasser trinken",
      "täglicher wasserbedarf",
      "wasserbedarf sport",
      "trinkmenge pro tag",
      "wasser pro kg körpergewicht",
      "dehydration vermeiden",
      "flüssigkeitsbedarf rechner",
      "wasserbedarf schwangerschaft"
    ],
    "icon": "💧"
  },
  {
    "slug": "koerperfett-rechner",
    "titel": "Körperfettrechner",
    "beschreibung": "Körperfettanteil schätzen mit der Navy-Methode: KFA in Prozent basierend auf Körpermaßen, mit Einordnung und Vergleich.",
    "kategorie": "Gesundheit",
    "kategorieSlug": "gesundheit",
    "keywords": [
      "körperfettrechner",
      "körperfettanteil berechnen",
      "kfa rechner",
      "navy methode körperfett",
      "körperfett messen",
      "body fat calculator",
      "körperfettanteil mann",
      "körperfettanteil frau",
      "körperfett prozent",
      "fettmasse berechnen"
    ],
    "icon": "📏"
  },
  {
    "slug": "ssw-rechner",
    "titel": "SSW-Rechner",
    "beschreibung": "Schwangerschaftswoche berechnen: Aktuelle SSW, Trimester und Entwicklung Ihres Babys Woche für Woche.",
    "kategorie": "Gesundheit",
    "kategorieSlug": "gesundheit",
    "keywords": [
      "ssw rechner",
      "schwangerschaftswoche berechnen",
      "ssw berechnen",
      "trimester rechner",
      "baby entwicklung",
      "wie viele wochen schwanger",
      "ssw tabelle",
      "mutterpass ssw",
      "geburtstermin",
      "schwangerschaftskalender"
    ],
    "icon": "🤰"
  },
  {
    "slug": "schwangerschaft-gewicht-rechner",
    "titel": "Gewichtszunahme-Rechner (Schwangerschaft)",
    "beschreibung": "Gewichtszunahme in der Schwangerschaft berechnen: Empfohlene Zunahme nach BMI, aktueller Stand und Verlaufskurve.",
    "kategorie": "Gesundheit",
    "kategorieSlug": "gesundheit",
    "keywords": [
      "gewichtszunahme schwangerschaft",
      "gewicht schwangerschaft rechner",
      "iom richtlinien",
      "schwangerschaft bmi",
      "zunahme pro woche schwangerschaft",
      "zwillinge gewichtszunahme"
    ],
    "icon": "🤰"
  },
  {
    "slug": "zyklusrechner",
    "titel": "Zyklusrechner",
    "beschreibung": "Eisprung, fruchtbares Fenster und nächste Periode berechnen — mit Kalenderansicht für 1, 3 oder 6 Zyklen.",
    "kategorie": "Gesundheit",
    "kategorieSlug": "gesundheit",
    "keywords": [
      "zyklusrechner",
      "eisprungrechner",
      "fruchtbare tage berechnen",
      "eisprung berechnen",
      "fruchtbares fenster",
      "menstruationszyklus rechner",
      "periode berechnen"
    ],
    "icon": "🔄"
  },
  {
    "slug": "alkohol-abbau-rechner",
    "titel": "Alkohol-Abbau-Rechner",
    "beschreibung": "Maximale Promille, Abbauzeit und wann Sie wieder nüchtern sind — berechnet nach der Widmark-Formel.",
    "kategorie": "Gesundheit",
    "kategorieSlug": "gesundheit",
    "keywords": [
      "alkohol abbau rechner",
      "promille abbau",
      "wann bin ich wieder nüchtern",
      "widmark formel",
      "alkohol fahrtauglich",
      "promille berechnen",
      "blutalkohol rechner"
    ],
    "icon": "🍺"
  },
  {
    "slug": "protein-rechner",
    "titel": "Protein-Rechner",
    "beschreibung": "Täglichen Proteinbedarf berechnen: Empfohlene Eiweißmenge nach Gewicht, Aktivität und Trainingsziel.",
    "kategorie": "Gesundheit",
    "kategorieSlug": "gesundheit",
    "keywords": [
      "protein rechner",
      "eiweißbedarf",
      "protein pro tag",
      "eiweiß berechnen",
      "muskelaufbau protein"
    ],
    "icon": "💪"
  },
  {
    "slug": "herzfrequenz-rechner",
    "titel": "Herzfrequenz-Rechner",
    "beschreibung": "Trainingszonen und Maximalpuls berechnen — für Fettverbrennung, Ausdauer und Intervall nach Karvonen.",
    "kategorie": "Gesundheit",
    "kategorieSlug": "gesundheit",
    "keywords": [
      "herzfrequenz rechner",
      "maximalpuls berechnen",
      "trainingszonen",
      "karvonen formel",
      "fettverbrennung puls",
      "grundlagenausdauer puls",
      "anaerobe schwelle",
      "ruhepuls",
      "zielpuls berechnen",
      "puls beim sport"
    ],
    "icon": "❤️"
  },
  {
    "slug": "whr-rechner",
    "titel": "WHR-Rechner",
    "beschreibung": "Taille-Hüfte-Verhältnis berechnen: WHR als Indikator für gesundheitliches Risiko — aussagekräftiger als der BMI.",
    "kategorie": "Gesundheit",
    "kategorieSlug": "gesundheit",
    "keywords": [
      "whr rechner",
      "taille hüfte verhältnis",
      "waist hip ratio",
      "whr berechnen",
      "bauchumfang verhältnis",
      "viszerales fett",
      "whtr rechner",
      "taille hüfte index"
    ],
    "icon": "📏"
  },
  {
    "slug": "blutdruck-rechner",
    "titel": "Blutdruck-Rechner",
    "beschreibung": "Blutdruckwerte einordnen: WHO-Klassifikation, Durchschnitt aus mehreren Messungen und Risikobewertung.",
    "kategorie": "Gesundheit",
    "kategorieSlug": "gesundheit",
    "keywords": [
      "blutdruck rechner",
      "blutdruck einordnen",
      "blutdruckwerte tabelle",
      "hypertonie",
      "blutdruck normal",
      "blutdruck messen",
      "systolisch diastolisch"
    ],
    "icon": "🩺"
  },
  {
    "slug": "schritte-rechner",
    "titel": "Schritte-Rechner",
    "beschreibung": "Schritte in Kilometer und Kalorien umrechnen: Tagesziel prüfen und Kalorienverbrauch durch Gehen berechnen.",
    "kategorie": "Gesundheit",
    "kategorieSlug": "gesundheit",
    "keywords": [
      "schritte rechner",
      "schritte in km",
      "schritte kalorien",
      "10000 schritte",
      "schrittlänge berechnen",
      "gehgeschwindigkeit",
      "kalorienverbrauch gehen"
    ],
    "icon": "🚶"
  },
  {
    "slug": "sonnenschutz-rechner",
    "titel": "Sonnenschutz-Rechner",
    "beschreibung": "Sonnenschutz berechnen: Eigenschutzzeit, empfohlener Lichtschutzfaktor und maximale Sonnenzeit.",
    "kategorie": "Gesundheit",
    "kategorieSlug": "gesundheit",
    "keywords": [
      "sonnenschutz rechner",
      "lsf rechner",
      "eigenschutzzeit",
      "uv index",
      "sonnencreme",
      "lichtschutzfaktor",
      "hauttyp"
    ],
    "icon": "☀️"
  },
  {
    "slug": "spritkosten-rechner",
    "titel": "Spritkostenrechner",
    "beschreibung": "Spritkosten und Fahrtkosten berechnen: Benzinverbrauch, Kosten pro Kilometer und Gesamtkosten für jede Strecke.",
    "kategorie": "Auto & Verkehr",
    "kategorieSlug": "auto",
    "keywords": [
      "spritkostenrechner",
      "spritkosten berechnen",
      "fahrtkosten rechner",
      "benzinkosten",
      "kosten pro km",
      "tankkosten berechnen"
    ],
    "icon": "⛽"
  },
  {
    "slug": "kw-ps-umrechner",
    "titel": "KW-PS-Umrechner",
    "beschreibung": "KW in PS umrechnen und umgekehrt: Sofort-Ergebnis mit Umrechnungstabelle für gängige Fahrzeuge.",
    "kategorie": "Auto & Verkehr",
    "kategorieSlug": "auto",
    "keywords": [
      "kw in ps",
      "ps in kw",
      "kw ps umrechner",
      "kilowatt ps",
      "ps umrechnen",
      "kw umrechnen"
    ],
    "icon": "🏎️"
  },
  {
    "slug": "kfz-steuer-rechner",
    "titel": "Kfz-Steuer-Rechner",
    "beschreibung": "Kfz-Steuer 2026 berechnen: Für Benziner, Diesel, Elektro und Hybrid. Mit Aufschlüsselung nach Hubraum und CO₂.",
    "kategorie": "Auto & Verkehr",
    "kategorieSlug": "auto",
    "keywords": [
      "kfz steuer rechner",
      "kfz steuer berechnen",
      "kfz steuer 2026",
      "autosteuer",
      "kraftfahrzeugsteuer",
      "co2 steuer auto"
    ],
    "icon": "🚙"
  },
  {
    "slug": "bussgeldrechner",
    "titel": "Bußgeldrechner",
    "beschreibung": "Bußgeld, Punkte und Fahrverbot für Verkehrsverstöße berechnen — basierend auf dem aktuellen Bußgeldkatalog 2026.",
    "kategorie": "Auto & Verkehr",
    "kategorieSlug": "auto",
    "keywords": [
      "bußgeldrechner",
      "bußgeld berechnen",
      "bußgeldkatalog 2026",
      "geschwindigkeitsüberschreitung",
      "punkte flensburg",
      "fahrverbot",
      "blitzer strafe",
      "rotlichtverstoß",
      "bußgeld geschwindigkeit",
      "verkehrsverstoß strafe"
    ],
    "icon": "🚨"
  },
  {
    "slug": "autokosten-rechner",
    "titel": "Autokosten-Rechner",
    "beschreibung": "Autokosten berechnen: Monatliche und jährliche Gesamtkosten Ihres Autos — von Versicherung über Sprit bis Wertverlust.",
    "kategorie": "Auto & Verkehr",
    "kategorieSlug": "auto",
    "keywords": [
      "autokosten rechner",
      "autokosten berechnen",
      "was kostet ein auto im monat",
      "autokosten pro km",
      "kosten auto pro monat",
      "wertverlust auto",
      "unterhaltskosten auto",
      "kfz kosten rechner",
      "auto gesamtkosten",
      "kosten pro kilometer"
    ],
    "icon": "🚗"
  },
  {
    "slug": "leasing-rechner",
    "titel": "Leasing-Rechner",
    "beschreibung": "Leasing berechnen: Leasingrate, Gesamtkosten und Vergleich Leasing vs. Finanzierung für Ihr Wunschfahrzeug.",
    "kategorie": "Auto & Verkehr",
    "kategorieSlug": "auto",
    "keywords": [
      "leasing rechner",
      "leasingrate berechnen",
      "leasingfaktor",
      "leasing vs finanzierung",
      "auto leasing",
      "leasing gesamtkosten",
      "mehrkilometer leasing",
      "leasing kosten"
    ],
    "icon": "🚘"
  },
  {
    "slug": "fuehrerschein-rechner",
    "titel": "Führerscheinkosten-Rechner",
    "beschreibung": "Führerscheinkosten berechnen: Gesamtkosten für Klasse B mit Fahrstunden, Prüfungsgebühren und Sehtest.",
    "kategorie": "Auto & Verkehr",
    "kategorieSlug": "auto",
    "keywords": [
      "führerscheinkosten",
      "führerschein kosten",
      "was kostet ein führerschein",
      "führerschein klasse b",
      "fahrschule kosten",
      "fahrstunden preis",
      "führerschein rechner",
      "führerscheinprüfung kosten"
    ],
    "icon": "🚗"
  },
  {
    "slug": "reichweiten-rechner",
    "titel": "Reichweiten-Rechner (E-Auto)",
    "beschreibung": "Realistische E-Auto-Reichweite berechnen — abhängig von Temperatur, Fahrprofil und Verbrauch.",
    "kategorie": "Auto & Verkehr",
    "kategorieSlug": "auto",
    "keywords": [
      "e-auto reichweite rechner",
      "wltp reichweite real",
      "elektroauto verbrauch",
      "e-auto winter reichweite",
      "kwh pro 100 km",
      "ladekosten rechner",
      "e-auto autobahn reichweite",
      "reichweite tesla",
      "e-auto stromverbrauch"
    ],
    "icon": "🔋"
  },
  {
    "slug": "fahrrad-rahmengroesse-rechner",
    "titel": "Fahrrad-Rahmengröße-Rechner",
    "beschreibung": "Optimale Fahrrad-Rahmengröße berechnen: Nach Körpergröße und Schrittlänge — für Rennrad, MTB, City und E-Bike.",
    "kategorie": "Auto & Verkehr",
    "kategorieSlug": "auto",
    "keywords": [
      "fahrrad rahmengröße",
      "rahmenhöhe berechnen",
      "fahrradgröße rechner",
      "schrittlänge fahrrad",
      "rennrad rahmengröße",
      "mtb rahmengröße",
      "e-bike rahmenhöhe"
    ],
    "icon": "🚲"
  },
  {
    "slug": "taxi-rechner",
    "titel": "Taxi-Kosten-Rechner",
    "beschreibung": "Taxikosten schätzen: Fahrpreis nach Strecke, Tarif und Stadt.",
    "kategorie": "Auto & Verkehr",
    "kategorieSlug": "auto",
    "keywords": [
      "taxi rechner",
      "taxikosten berechnen",
      "taxi preis",
      "taxi tarif",
      "taxifahrt kosten",
      "taxi berlin",
      "taxi münchen"
    ],
    "icon": "🚕"
  },
  {
    "slug": "stromkosten-rechner",
    "titel": "Stromkostenrechner",
    "beschreibung": "Stromkosten berechnen: Jahresverbrauch, Arbeitspreis und Grundpreis — mit Haushaltsgröße-Schnellwahl.",
    "kategorie": "Wohnen & Energie",
    "kategorieSlug": "wohnen",
    "keywords": [
      "stromkosten rechner",
      "stromkosten berechnen",
      "stromverbrauch kosten",
      "strompreis rechner",
      "kwh kosten"
    ],
    "icon": "⚡"
  },
  {
    "slug": "nebenkosten-rechner",
    "titel": "Nebenkostenrechner",
    "beschreibung": "Mietnebenkosten berechnen: Alle Posten von Heizung bis Müll — mit Warmmiete und Kosten pro m².",
    "kategorie": "Wohnen & Energie",
    "kategorieSlug": "wohnen",
    "keywords": [
      "nebenkosten rechner",
      "nebenkosten berechnen",
      "mietnebenkosten",
      "betriebskosten rechner",
      "warmmiete berechnen"
    ],
    "icon": "🏢"
  },
  {
    "slug": "mietrechner",
    "titel": "Mietrechner",
    "beschreibung": "Warmmiete berechnen und Mietbelastung prüfen: Kaltmiete, Nebenkosten und Mietbelastungsquote.",
    "kategorie": "Wohnen & Energie",
    "kategorieSlug": "wohnen",
    "keywords": [
      "mietrechner",
      "mietbelastung",
      "warmmiete berechnen",
      "miete berechnen",
      "mietpreis rechner",
      "miete einkommen"
    ],
    "icon": "🔑"
  },
  {
    "slug": "heizkosten-rechner",
    "titel": "Heizkostenrechner",
    "beschreibung": "Heizkosten berechnen: Gas, Öl, Fernwärme, Wärmepumpe oder Pellets — mit Energieträger-Vergleich.",
    "kategorie": "Wohnen & Energie",
    "kategorieSlug": "wohnen",
    "keywords": [
      "heizkosten rechner",
      "heizkosten berechnen",
      "gaskosten rechner",
      "heizung kosten",
      "energiekosten rechner"
    ],
    "icon": "🔥"
  },
  {
    "slug": "grunderwerbsteuer-rechner",
    "titel": "Grunderwerbsteuerrechner",
    "beschreibung": "Grunderwerbsteuer und Kaufnebenkosten berechnen: Nach Bundesland mit Makler, Notar und Grundbuch.",
    "kategorie": "Wohnen & Energie",
    "kategorieSlug": "wohnen",
    "keywords": [
      "grunderwerbsteuer rechner",
      "grunderwerbsteuer",
      "kaufnebenkosten rechner",
      "immobilien nebenkosten",
      "grunderwerbsteuer bundesland"
    ],
    "icon": "🏡"
  },
  {
    "slug": "baufinanzierung-rechner",
    "titel": "Baufinanzierungs-Rechner",
    "beschreibung": "Baufinanzierung berechnen: Monatsrate, Gesamtkosten, Restschuld und Tilgungsplan für Ihre Immobilienfinanzierung.",
    "kategorie": "Wohnen & Energie",
    "kategorieSlug": "wohnen",
    "keywords": [
      "baufinanzierung rechner",
      "baufinanzierung berechnen",
      "immobilienkredit rechner",
      "hypothekenrechner",
      "monatsrate immobilie",
      "tilgungsplan",
      "restschuld berechnen",
      "immobilienfinanzierung",
      "hauskauf rechner",
      "baukredit rechner"
    ],
    "icon": "🏗️"
  },
  {
    "slug": "quadratmeter-rechner",
    "titel": "Quadratmeter-Rechner",
    "beschreibung": "Fläche in m² berechnen: Rechteck, Kreis, Dreieck, L-Form, Trapez. Mehrere Flächen addieren.",
    "kategorie": "Wohnen & Energie",
    "kategorieSlug": "wohnen",
    "keywords": [
      "quadratmeter rechner",
      "fläche berechnen",
      "qm rechner",
      "m2 rechner",
      "flächenrechner",
      "wohnfläche berechnen",
      "quadratmeter berechnen formel"
    ],
    "icon": "📐"
  },
  {
    "slug": "tapetenbedarf-rechner",
    "titel": "Tapetenbedarf-Rechner",
    "beschreibung": "Tapetenbedarf berechnen: Rollen-Anzahl mit Rapport, Verschnitt und Abzügen für Fenster & Türen.",
    "kategorie": "Wohnen & Energie",
    "kategorieSlug": "wohnen",
    "keywords": [
      "tapetenbedarf rechner",
      "tapetenrollen berechnen",
      "wie viele rollen tapete",
      "tapetenbedarf berechnen",
      "rapport tapete",
      "verschnitt tapete",
      "tapetenbedarf online rechner"
    ],
    "icon": "🖼️"
  },
  {
    "slug": "stromvergleich-rechner",
    "titel": "Stromvergleich-Rechner",
    "beschreibung": "Stromanbieter vergleichen: Aktuelle Kosten berechnen, Sparpotenzial ermitteln und günstigere Tarife finden.",
    "kategorie": "Wohnen & Energie",
    "kategorieSlug": "wohnen",
    "keywords": [
      "stromvergleich rechner",
      "stromanbieter vergleichen",
      "stromkosten vergleich",
      "strom sparen",
      "günstiger strom",
      "stromtarif vergleichen",
      "ökostrom vergleich",
      "strompreis vergleich",
      "stromanbieter wechseln",
      "stromvergleich 2026"
    ],
    "icon": "🔌"
  },
  {
    "slug": "mietrendite-rechner",
    "titel": "Mietrendite-Rechner",
    "beschreibung": "Mietrendite berechnen: Brutto- und Nettomietrendite für Immobilien als Kapitalanlage, mit Cashflow-Analyse.",
    "kategorie": "Wohnen & Energie",
    "kategorieSlug": "wohnen",
    "keywords": [
      "mietrendite rechner",
      "mietrendite berechnen",
      "bruttomietrendite",
      "nettomietrendite",
      "eigenkapitalrendite immobilie",
      "immobilie als kapitalanlage",
      "mietmultiplikator",
      "cashflow immobilie",
      "rendite immobilie berechnen",
      "immobilienrendite"
    ],
    "icon": "📊"
  },
  {
    "slug": "indexmiete-rechner",
    "titel": "Indexmiete-Rechner",
    "beschreibung": "Indexmiete berechnen: Mieterhöhung bei Indexmietvertrag basierend auf dem Verbraucherpreisindex (VPI).",
    "kategorie": "Wohnen & Energie",
    "kategorieSlug": "wohnen",
    "keywords": [
      "indexmiete rechner",
      "indexmiete berechnen",
      "indexmietvertrag",
      "vpi mieterhöhung",
      "verbraucherpreisindex miete",
      "mieterhöhung indexmiete",
      "indexmiete erhöhung",
      "staffelmiete vs indexmiete",
      "destatis vpi",
      "mietanpassung"
    ],
    "icon": "📈"
  },
  {
    "slug": "waermepumpen-rechner",
    "titel": "Wärmepumpen-Rechner",
    "beschreibung": "Wärmepumpe berechnen: Betriebskosten, Amortisation und Kostenvergleich mit Gasheizung — lohnt sich der Umstieg?",
    "kategorie": "Wohnen & Energie",
    "kategorieSlug": "wohnen",
    "keywords": [
      "wärmepumpe rechner",
      "wärmepumpe kosten",
      "wärmepumpe amortisation",
      "beg förderung 2026",
      "jahresarbeitszahl jaz",
      "wärmepumpe altbau",
      "wärmepumpe vs gas",
      "wärmepumpen stromtarif",
      "heizung tauschen",
      "luft wasser wärmepumpe"
    ],
    "icon": "🔥"
  },
  {
    "slug": "photovoltaik-rechner",
    "titel": "Photovoltaik-Rechner",
    "beschreibung": "Photovoltaik-Anlage berechnen: Ertrag, Eigenverbrauch, Einspeisevergütung und Amortisation Ihrer Solaranlage.",
    "kategorie": "Wohnen & Energie",
    "kategorieSlug": "wohnen",
    "keywords": [
      "photovoltaik rechner",
      "pv rechner",
      "solaranlage berechnen",
      "einspeisevergütung 2026",
      "photovoltaik amortisation",
      "solarrechner",
      "pv ertrag berechnen",
      "batteriespeicher rechner"
    ],
    "icon": "☀️"
  },
  {
    "slug": "dachflaechen-rechner",
    "titel": "Dachflächen-Rechner",
    "beschreibung": "Dachfläche berechnen: Satteldach, Pultdach, Walmdach oder Flachdach — mit Material- und PV-Potenzial.",
    "kategorie": "Wohnen & Energie",
    "kategorieSlug": "wohnen",
    "keywords": [
      "dachfläche berechnen",
      "dachflächen rechner",
      "dachneigung",
      "satteldach fläche",
      "pultdach berechnen",
      "walmdach fläche",
      "dachziegel berechnen",
      "sparrenlänge"
    ],
    "icon": "🏠"
  },
  {
    "slug": "malerkosten-rechner",
    "titel": "Malerkosten-Rechner",
    "beschreibung": "Streichkosten für Wand und Decke berechnen — Farbbedarf, Material und Malerkosten mit Einkaufsliste.",
    "kategorie": "Wohnen & Energie",
    "kategorieSlug": "wohnen",
    "keywords": [
      "malerkosten rechner",
      "streichen kosten",
      "farbbedarf rechner",
      "maler kosten",
      "wand streichen kosten",
      "decke streichen",
      "wandfarbe menge",
      "streichfläche berechnen"
    ],
    "icon": "🎨"
  },
  {
    "slug": "grundsteuer-rechner",
    "titel": "Grundsteuer-Rechner",
    "beschreibung": "Neue Grundsteuer berechnen: Grundsteuerwert, Steuermessbetrag und jährliche Grundsteuer nach dem Bundesmodell.",
    "kategorie": "Wohnen & Energie",
    "kategorieSlug": "wohnen",
    "keywords": [
      "grundsteuer rechner",
      "grundsteuer 2026",
      "grundsteuerreform",
      "bodenrichtwert",
      "hebesatz",
      "grundsteuerwert",
      "bundesmodell grundsteuer",
      "grundsteuer bayern",
      "grundsteuer baden-württemberg"
    ],
    "icon": "🏠"
  },
  {
    "slug": "mietpreisbremse-rechner",
    "titel": "Mietpreisbremse-Rechner",
    "beschreibung": "Mietpreisbremse prüfen: Ist Ihre Miete zulässig und wie viel können Sie zurückfordern?",
    "kategorie": "Wohnen & Energie",
    "kategorieSlug": "wohnen",
    "keywords": [
      "mietpreisbremse",
      "mietpreisbremse rechner",
      "miete zu hoch",
      "vergleichsmiete",
      "ortsübliche miete",
      "mietspiegel",
      "mietminderung",
      "rüge vermieter",
      "miete zurückfordern"
    ],
    "icon": "🏠"
  },
  {
    "slug": "poolkosten-rechner",
    "titel": "Poolkosten-Rechner",
    "beschreibung": "Jährliche Betriebskosten für Pool: Wasser, Strom, Chemie und Wartung — mit Heizung und Abdeckung.",
    "kategorie": "Wohnen & Energie",
    "kategorieSlug": "wohnen",
    "keywords": [
      "poolkosten rechner",
      "pool betriebskosten",
      "pool strom kosten",
      "pool chemie kosten",
      "pool wärmepumpe kosten",
      "pool wasser kosten",
      "pool unterhalt",
      "swimmingpool kosten jahr"
    ],
    "icon": "🏊"
  },
  {
    "slug": "vorfaelligkeitsentschaedigung-rechner",
    "titel": "Vorfälligkeitsentschädigung-Rechner",
    "beschreibung": "Vorfälligkeitsentschädigung berechnen: Geschätzte Kosten bei vorzeitiger Kreditablösung nach der Aktiv-Passiv-Methode.",
    "kategorie": "Wohnen & Energie",
    "kategorieSlug": "wohnen",
    "keywords": [
      "vorfälligkeitsentschädigung berechnen",
      "vfe rechner",
      "kredit ablösen",
      "baufinanzierung vorzeitig kündigen",
      "aktiv passiv methode",
      "10 jahre sonderkündigungsrecht",
      "§ 489 bgb",
      "umschuldung",
      "restschuld ablösen"
    ],
    "icon": "🏦"
  },
  {
    "slug": "energiekosten-rechner",
    "titel": "Energiekosten-Rechner",
    "beschreibung": "Stromkosten für einzelne Geräte berechnen: Tägliche, monatliche und jährliche Energiekosten pro Gerät.",
    "kategorie": "Wohnen & Energie",
    "kategorieSlug": "wohnen",
    "keywords": [
      "energiekosten rechner",
      "stromkosten gerät berechnen",
      "watt in kwh",
      "verbrauch berechnen",
      "standby kosten",
      "kühlschrank stromkosten",
      "waschmaschine stromkosten",
      "stromverbrauch haushalt",
      "kwh kosten"
    ],
    "icon": "⚡"
  },
  {
    "slug": "fliesenbedarf-rechner",
    "titel": "Fliesenbedarf-Rechner",
    "beschreibung": "Fliesenbedarf berechnen: Anzahl Fliesen, Fliesenkleber und Fugenmasse für Boden und Wand.",
    "kategorie": "Wohnen & Energie",
    "kategorieSlug": "wohnen",
    "keywords": [
      "fliesenbedarf rechner",
      "fliesen berechnen",
      "fliesenbedarf berechnen",
      "fliesenkleber berechnen",
      "fugenmasse berechnen",
      "fliesen pro qm",
      "verschnitt fliesen",
      "fliesenrechner"
    ],
    "icon": "🧱"
  },
  {
    "slug": "laminat-rechner",
    "titel": "Laminat-Rechner",
    "beschreibung": "Laminat- und Parkettbedarf berechnen: Pakete, Verschnitt und Materialkosten.",
    "kategorie": "Wohnen & Energie",
    "kategorieSlug": "wohnen",
    "keywords": [
      "laminat rechner",
      "laminat berechnen",
      "parkett rechner",
      "laminat pakete berechnen",
      "verschnitt laminat",
      "laminat m2 rechner",
      "laminatbedarf",
      "parkett bedarf"
    ],
    "icon": "🪵"
  },
  {
    "slug": "beton-rechner",
    "titel": "Beton-Rechner",
    "beschreibung": "Betonmenge berechnen: Kubikmeter und benötigte Säcke für Fundament, Bodenplatte und Pfosten.",
    "kategorie": "Wohnen & Energie",
    "kategorieSlug": "wohnen",
    "keywords": [
      "beton rechner",
      "betonmenge berechnen",
      "beton säcke",
      "fundament beton",
      "beton kubikmeter",
      "fertigbeton",
      "lieferbeton"
    ],
    "icon": "🧱"
  },
  {
    "slug": "estrich-rechner",
    "titel": "Estrich-Rechner",
    "beschreibung": "Estrich- und Putzmenge berechnen: Materialbedarf in kg und Säcke für Boden und Wand.",
    "kategorie": "Wohnen & Energie",
    "kategorieSlug": "wohnen",
    "keywords": [
      "estrich rechner",
      "estrich menge berechnen",
      "estrich bedarf",
      "putz rechner",
      "verputz menge",
      "zementestrich",
      "fließestrich"
    ],
    "icon": "🏗️"
  },
  {
    "slug": "balkon-solar-rechner",
    "titel": "Balkon-Solar-Rechner",
    "beschreibung": "Balkon-Solaranlage berechnen: Ertrag, Eigenverbrauch und Amortisation für 600W/800W Balkonkraftwerke.",
    "kategorie": "Wohnen & Energie",
    "kategorieSlug": "wohnen",
    "keywords": [
      "balkonkraftwerk rechner",
      "balkon solar rechner",
      "balkonkraftwerk ertrag",
      "balkonkraftwerk amortisation",
      "800 watt balkonkraftwerk",
      "mini pv anlage",
      "stecker solaranlage"
    ],
    "icon": "☀️"
  },
  {
    "slug": "bruchrechner",
    "titel": "Bruchrechner",
    "beschreibung": "Brüche berechnen: Addieren, subtrahieren, multiplizieren, dividieren. Mit Rechenweg, Kürzen und Umrechnung.",
    "kategorie": "Mathe & Schule",
    "kategorieSlug": "mathe",
    "keywords": [
      "bruchrechner",
      "brüche berechnen",
      "bruch kürzen",
      "bruchrechnung",
      "brüche addieren",
      "brüche multiplizieren",
      "dezimalzahl in bruch"
    ],
    "icon": "🔢"
  },
  {
    "slug": "einheiten-umrechner",
    "titel": "Einheiten-Umrechner",
    "beschreibung": "Einheiten umrechnen: Länge, Gewicht, Volumen, Fläche, Temperatur, Zeit, Geschwindigkeit und Daten.",
    "kategorie": "Mathe & Schule",
    "kategorieSlug": "mathe",
    "keywords": [
      "einheiten umrechner",
      "einheiten umrechnen",
      "längeneinheiten umrechnen",
      "gewicht umrechnen",
      "temperatur umrechnen",
      "volumen umrechnen",
      "zoll in cm",
      "fahrenheit in celsius"
    ],
    "icon": "📏"
  },
  {
    "slug": "notenschluessel-rechner",
    "titel": "Notenschlüssel-Rechner",
    "beschreibung": "Punkte in Noten umrechnen, Notenschlüssel erstellen und Notendurchschnitt berechnen. Schulnoten, IHK & Uni.",
    "kategorie": "Mathe & Schule",
    "kategorieSlug": "mathe",
    "keywords": [
      "notenschlüssel rechner",
      "punkte in noten",
      "notenschlüssel erstellen",
      "notendurchschnitt berechnen",
      "ihk notenschlüssel",
      "notenrechner",
      "schulnoten berechnen"
    ],
    "icon": "📝"
  },
  {
    "slug": "durchschnitt-rechner",
    "titel": "Durchschnittsrechner",
    "beschreibung": "Durchschnitt berechnen: Arithmetisches & gewichtetes Mittel, Median, Modus und Standardabweichung.",
    "kategorie": "Mathe & Schule",
    "kategorieSlug": "mathe",
    "keywords": [
      "durchschnitt berechnen",
      "mittelwert rechner",
      "durchschnittsrechner",
      "gewichteter durchschnitt",
      "median berechnen",
      "modus berechnen",
      "standardabweichung"
    ],
    "icon": "📊"
  },
  {
    "slug": "wissenschaftlicher-taschenrechner",
    "titel": "Wissenschaftlicher Taschenrechner",
    "beschreibung": "Wissenschaftlicher Taschenrechner online: Trigonometrie, Logarithmen, Potenzen, Klammern und mehr.",
    "kategorie": "Mathe & Schule",
    "kategorieSlug": "mathe",
    "keywords": [
      "wissenschaftlicher taschenrechner",
      "taschenrechner online",
      "scientific calculator",
      "sin cos tan rechner",
      "logarithmus rechner",
      "potenzrechner",
      "fakultät berechnen"
    ],
    "icon": "🧮"
  },
  {
    "slug": "flaechenrechner",
    "titel": "Flächenrechner",
    "beschreibung": "Fläche und Umfang berechnen: Für Rechteck, Dreieck, Kreis, Trapez, Parallelogramm und weitere Formen.",
    "kategorie": "Mathe & Schule",
    "kategorieSlug": "mathe",
    "keywords": [
      "flächenrechner",
      "fläche berechnen",
      "umfang berechnen",
      "fläche rechteck",
      "fläche kreis",
      "fläche dreieck",
      "trapez fläche",
      "parallelogramm fläche",
      "geometrie rechner",
      "flächenberechnung"
    ],
    "icon": "📐"
  },
  {
    "slug": "prozentuale-veraenderung-rechner",
    "titel": "Prozentuale-Veränderung-Rechner",
    "beschreibung": "Prozentuale Veränderung berechnen: Zu- oder Abnahme zwischen zwei Werten in Prozent, mit Rechenweg.",
    "kategorie": "Mathe & Schule",
    "kategorieSlug": "mathe",
    "keywords": [
      "prozentuale veränderung berechnen",
      "prozentuale zunahme",
      "prozentuale abnahme",
      "veränderung in prozent",
      "prozentrechner veränderung",
      "steigerung in prozent berechnen",
      "rückgang in prozent",
      "prozentuale differenz",
      "wachstumsrate berechnen",
      "relative veränderung"
    ],
    "icon": "📉"
  },
  {
    "slug": "volumenrechner",
    "titel": "Volumen-Rechner",
    "beschreibung": "Volumen und Oberfläche berechnen: Für Quader, Zylinder, Kugel, Kegel, Pyramide und weitere Körper.",
    "kategorie": "Mathe & Schule",
    "kategorieSlug": "mathe",
    "keywords": [
      "volumenrechner",
      "volumen berechnen",
      "oberflaeche berechnen",
      "quader volumen",
      "zylinder volumen",
      "kugel volumen",
      "kegel volumen",
      "pyramide volumen",
      "cm3 in liter",
      "volumen formel"
    ],
    "icon": "📦"
  },
  {
    "slug": "abi-rechner",
    "titel": "Abi-Notenrechner",
    "beschreibung": "Abitur-Durchschnittsnote berechnen: Von Punkten zur Abi-Note — mit Block I (Kurse) und Block II (Prüfungen).",
    "kategorie": "Mathe & Schule",
    "kategorieSlug": "mathe",
    "keywords": [
      "abi rechner",
      "abiturnote berechnen",
      "abi punkte note",
      "abinote rechner",
      "block i block ii",
      "abitur durchschnitt",
      "abi note formel"
    ],
    "icon": "🎓"
  },
  {
    "slug": "binaer-rechner",
    "titel": "Binär-Rechner",
    "beschreibung": "Zahlen zwischen Dezimal, Binär, Oktal und Hexadezimal live umrechnen — mit Rechenweg und ASCII-Code.",
    "kategorie": "Mathe & Schule",
    "kategorieSlug": "mathe",
    "keywords": [
      "binär rechner",
      "dezimal binär umrechnen",
      "binärcode",
      "hex umrechnen",
      "oktal",
      "zahlensystem umrechnen",
      "binäre zahlen",
      "zweierpotenz"
    ],
    "icon": "💻"
  },
  {
    "slug": "pythagoras-rechner",
    "titel": "Pythagoras-Rechner",
    "beschreibung": "Satz des Pythagoras berechnen: Fehlende Seite im rechtwinkligen Dreieck — mit Rechenweg und Grafik.",
    "kategorie": "Mathe & Schule",
    "kategorieSlug": "mathe",
    "keywords": [
      "pythagoras rechner",
      "satz des pythagoras",
      "hypotenuse berechnen",
      "kathete berechnen",
      "rechtwinkliges dreieck",
      "a² + b² = c²",
      "pythagoras formel",
      "dreieck seite berechnen"
    ],
    "icon": "📐"
  },
  {
    "slug": "gleichungsrechner",
    "titel": "Gleichungslöser",
    "beschreibung": "Lineare und quadratische Gleichungen lösen — mit vollständigem Rechenweg, Mitternachtsformel und Parabel-Grafik.",
    "kategorie": "Mathe & Schule",
    "kategorieSlug": "mathe",
    "keywords": [
      "gleichungsrechner",
      "gleichungen lösen",
      "lineare gleichung",
      "quadratische gleichung",
      "mitternachtsformel",
      "pq-formel",
      "nullstellen berechnen",
      "diskriminante"
    ],
    "icon": "📝"
  },
  {
    "slug": "primzahl-rechner",
    "titel": "Primzahl-Rechner",
    "beschreibung": "Primzahlen prüfen und finden: Ist eine Zahl prim? Primfaktorzerlegung und Primzahlen in einem Bereich.",
    "kategorie": "Mathe & Schule",
    "kategorieSlug": "mathe",
    "keywords": [
      "primzahl rechner",
      "primzahlen",
      "primfaktorzerlegung",
      "ist primzahl",
      "primzahl prüfen",
      "primzahlen liste",
      "sieb des eratosthenes",
      "faktorzerlegung"
    ],
    "icon": "🔢"
  },
  {
    "slug": "quersumme-rechner",
    "titel": "Quersumme-Rechner",
    "beschreibung": "Quersumme berechnen: Einstellige und alternierende Quersumme — mit Teilbarkeitsregeln.",
    "kategorie": "Mathe & Schule",
    "kategorieSlug": "mathe",
    "keywords": [
      "quersumme rechner",
      "quersumme berechnen",
      "iterierte quersumme",
      "alternierende quersumme",
      "teilbarkeitsregeln",
      "quersummenregel",
      "ziffernquersumme"
    ],
    "icon": "➕"
  },
  {
    "slug": "potenz-rechner",
    "titel": "Potenz-Rechner",
    "beschreibung": "Potenzen, Wurzeln und Logarithmen berechnen mit Rechenweg und Potenzgesetzen.",
    "kategorie": "Mathe & Schule",
    "kategorieSlug": "mathe",
    "keywords": [
      "potenzrechner",
      "potenz berechnen",
      "wurzel berechnen",
      "logarithmus rechner",
      "potenzgesetze",
      "quadratwurzel",
      "exponenten"
    ],
    "icon": "🔢"
  },
  {
    "slug": "ggt-kgv-rechner",
    "titel": "ggT/kgV-Rechner",
    "beschreibung": "Größten gemeinsamen Teiler und kleinstes gemeinsames Vielfaches berechnen.",
    "kategorie": "Mathe & Schule",
    "kategorieSlug": "mathe",
    "keywords": [
      "ggt rechner",
      "kgv rechner",
      "größter gemeinsamer teiler",
      "kleinstes gemeinsames vielfaches",
      "euklidischer algorithmus",
      "primfaktorzerlegung"
    ],
    "icon": "🔢"
  },
  {
    "slug": "zufallszahl-generator",
    "titel": "Zufallszahl-Generator",
    "beschreibung": "Zufallszahlen generieren: Zahlen, Würfel, Münzwurf, Losziehung und Passwort-Generator.",
    "kategorie": "Mathe & Schule",
    "kategorieSlug": "mathe",
    "keywords": [
      "zufallszahl generator",
      "würfel online",
      "münzwurf",
      "lotto zahlen generator",
      "passwort generator",
      "zufallsgenerator",
      "random number"
    ],
    "icon": "🎲"
  },
  {
    "slug": "noten-international",
    "titel": "Noten-Umrechner (international)",
    "beschreibung": "Noten international umrechnen: Deutsche Note ↔ GPA (USA) ↔ UK Classification ↔ ECTS-Grade.",
    "kategorie": "Mathe & Schule",
    "kategorieSlug": "mathe",
    "keywords": [
      "noten umrechnen",
      "gpa rechner",
      "deutsche note gpa",
      "ects note",
      "uk classification",
      "noten international",
      "bayerische formel",
      "notenumrechner",
      "gpa in deutsche note"
    ],
    "icon": "🌍"
  },
  {
    "slug": "arbeitszeitrechner",
    "titel": "Arbeitszeitrechner",
    "beschreibung": "Arbeitszeit berechnen: Tägliche und wöchentliche Arbeitszeit mit Pausen, Dezimalzeit und gesetzlichen Hinweisen.",
    "kategorie": "Arbeit & Recht",
    "kategorieSlug": "arbeit",
    "keywords": [
      "arbeitszeitrechner",
      "arbeitszeit berechnen",
      "industrieminuten",
      "dezimalzeit",
      "arbeitszeit mit pausen",
      "wöchentliche arbeitszeit",
      "arbeitszeitgesetz"
    ],
    "icon": "⏱️"
  },
  {
    "slug": "urlaubstage-rechner",
    "titel": "Urlaubstage-Rechner",
    "beschreibung": "Urlaubsanspruch berechnen: Gesetzlicher und vertraglicher Urlaub, Teilzeit, Schwerbehinderung & Resturlaub bei Kündigung.",
    "kategorie": "Arbeit & Recht",
    "kategorieSlug": "arbeit",
    "keywords": [
      "urlaubstage rechner",
      "urlaubsanspruch berechnen",
      "resturlaub kündigung",
      "urlaubsanspruch teilzeit",
      "gesetzlicher mindesturlaub",
      "zusatzurlaub schwerbehinderung",
      "urlaubsabgeltung"
    ],
    "icon": "🏖️"
  },
  {
    "slug": "ueberstunden-rechner",
    "titel": "Überstunden-Rechner",
    "beschreibung": "Überstunden berechnen: Pro Woche, Monat und Jahr mit Vergütung, Zuschlag und Stundenlohn-Ermittlung.",
    "kategorie": "Arbeit & Recht",
    "kategorieSlug": "arbeit",
    "keywords": [
      "überstunden rechner",
      "überstunden berechnen",
      "überstundenvergütung",
      "überstundenzuschlag",
      "stundenlohn berechnen",
      "minusstunden",
      "mehrarbeit berechnen"
    ],
    "icon": "⏰"
  },
  {
    "slug": "pendlerpauschale-rechner",
    "titel": "Pendlerpauschale-Rechner",
    "beschreibung": "Pendlerpauschale 2026 berechnen: Entfernungspauschale, Steuerersparnis und Vergleich mit der Homeoffice-Pauschale.",
    "kategorie": "Arbeit & Recht",
    "kategorieSlug": "arbeit",
    "keywords": [
      "pendlerpauschale rechner",
      "entfernungspauschale 2026",
      "pendlerpauschale berechnen",
      "fahrtkostenpauschale",
      "pendlerpauschale steuerersparnis",
      "homeoffice pauschale vergleich",
      "km pauschale"
    ],
    "icon": "🛣️"
  },
  {
    "slug": "promillerechner",
    "titel": "Promillerechner",
    "beschreibung": "Blutalkohol berechnen: Nach Bier, Wein oder Schnaps den Promillewert schätzen, mit Abbau-Countdown und Grenzwert-Hinweisen.",
    "kategorie": "Arbeit & Recht",
    "kategorieSlug": "arbeit",
    "keywords": [
      "promillerechner",
      "promille berechnen",
      "blutalkohol rechner",
      "alkohol abbauen",
      "promille nach bier",
      "widmark formel",
      "alkohol grenzwerte"
    ],
    "icon": "🍺"
  },
  {
    "slug": "rechtsschutz-rechner",
    "titel": "Rechtsschutz-Rechner",
    "beschreibung": "Rechtsschutzversicherung berechnen: Geschätzte Kosten nach Bausteinen, Selbstbeteiligung und Lebenssituation.",
    "kategorie": "Arbeit & Recht",
    "kategorieSlug": "arbeit",
    "keywords": [
      "rechtsschutzversicherung rechner",
      "rechtsschutz kosten",
      "rechtsschutzversicherung kosten",
      "rechtsschutz beitrag",
      "rechtsschutzversicherung vergleich",
      "rechtsschutz monatlich",
      "arbeitsrechtsschutz",
      "verkehrsrechtsschutz",
      "privatrechtsschutz",
      "mietrechtsschutz"
    ],
    "icon": "🛡️"
  },
  {
    "slug": "freelancer-stundensatz-rechner",
    "titel": "Freelancer-Stundensatz-Rechner",
    "beschreibung": "Freelancer-Stundensatz berechnen: Vom Wunsch-Netto zum nötigen Stundensatz inkl. Steuern, Versicherungen und Betriebskosten.",
    "kategorie": "Arbeit & Recht",
    "kategorieSlug": "arbeit",
    "keywords": [
      "freelancer stundensatz rechner",
      "stundensatz berechnen freelancer",
      "stundensatz selbstständige",
      "freelancer stundensatz kalkulation",
      "selbstständig stundensatz",
      "freiberufler stundensatz",
      "stundensatz berechnen",
      "tagessatz freelancer",
      "freelancer honorar",
      "stundensatz kalkulator"
    ],
    "icon": "🖥️"
  },
  {
    "slug": "kuendigungsfrist-rechner",
    "titel": "Kündigungsfrist-Rechner",
    "beschreibung": "Gesetzliche Kündigungsfrist berechnen: Für Arbeitnehmer und Arbeitgeber, mit frühestmöglichem Austrittsdatum und relevanten Fristen.",
    "kategorie": "Arbeit & Recht",
    "kategorieSlug": "arbeit",
    "keywords": [
      "kündigungsfrist berechnen",
      "kündigungsfrist rechner",
      "gesetzliche kündigungsfrist",
      "kündigungsfrist arbeitnehmer",
      "kündigungsfrist arbeitgeber",
      "622 bgb",
      "letzter arbeitstag berechnen",
      "kündigungsfrist probezeit"
    ],
    "icon": "📋"
  },
  {
    "slug": "teilzeit-rechner",
    "titel": "Teilzeit-Rechner",
    "beschreibung": "Teilzeitgehalt berechnen: Brutto, geschätztes Netto, Stundenlohn und Urlaubstage bei Reduzierung der Arbeitszeit.",
    "kategorie": "Arbeit & Recht",
    "kategorieSlug": "arbeit",
    "keywords": [
      "teilzeit rechner",
      "teilzeitgehalt berechnen",
      "gehalt bei teilzeit",
      "teilzeit netto",
      "teilzeit brutto",
      "stundenlohn teilzeit",
      "urlaubstage teilzeit",
      "teilzeit berechnen"
    ],
    "icon": "⏰"
  },
  {
    "slug": "abfindungsrechner",
    "titel": "Abfindungsrechner",
    "beschreibung": "Abfindung berechnen: Regelabfindung, Netto-Abfindung nach Fünftelregelung und steuerliche Auswirkungen auf einen Blick.",
    "kategorie": "Arbeit & Recht",
    "kategorieSlug": "arbeit",
    "keywords": [
      "abfindungsrechner",
      "abfindung berechnen",
      "netto abfindung",
      "fünftelregelung",
      "abfindung versteuern",
      "regelabfindung berechnen",
      "abfindung steuer",
      "abfindungsrechner 2026"
    ],
    "icon": "💰"
  },
  {
    "slug": "mutterschutz-rechner",
    "titel": "Mutterschutz-Rechner",
    "beschreibung": "Mutterschutz berechnen: Beginn, Ende, Dauer und Mutterschaftsgeld — mit allen Fristen auf einen Blick.",
    "kategorie": "Arbeit & Recht",
    "kategorieSlug": "arbeit",
    "keywords": [
      "mutterschutz rechner",
      "mutterschutz berechnen",
      "mutterschutzfrist berechnen",
      "mutterschaftsgeld berechnen",
      "mutterschutz beginn",
      "mutterschutz dauer",
      "mutterschutz ende",
      "mutterschutz frühgeburt"
    ],
    "icon": "🤱"
  },
  {
    "slug": "scheidungskosten-rechner",
    "titel": "Scheidungskosten-Rechner",
    "beschreibung": "Scheidungskosten berechnen: Gerichtskosten, Anwaltskosten, Verfahrenswert — einvernehmlich vs. streitig im Vergleich.",
    "kategorie": "Arbeit & Recht",
    "kategorieSlug": "arbeit",
    "keywords": [
      "scheidungskosten rechner",
      "was kostet eine scheidung",
      "scheidungskosten 2026",
      "anwaltskosten scheidung",
      "gerichtskosten scheidung",
      "verfahrenswert scheidung",
      "einvernehmliche scheidung",
      "streitige scheidung",
      "verfahrenskostenhilfe",
      "scheidung kosten"
    ],
    "icon": "⚖️"
  },
  {
    "slug": "zugewinnausgleich-rechner",
    "titel": "Zugewinnausgleich-Rechner",
    "beschreibung": "Zugewinnausgleich berechnen: Zugewinn beider Ehepartner und Ausgleichsanspruch bei Scheidung oder Erbfall.",
    "kategorie": "Arbeit & Recht",
    "kategorieSlug": "arbeit",
    "keywords": [
      "zugewinnausgleich rechner",
      "zugewinn berechnen",
      "ausgleichsanspruch scheidung",
      "zugewinngemeinschaft",
      "anfangsvermögen endvermögen",
      "§ 1373 bgb",
      "privilegierter erwerb",
      "zugewinnausgleich formel",
      "ehevertrag zugewinn",
      "vermögensauseinandersetzung"
    ],
    "icon": "⚖️"
  },
  {
    "slug": "arbeitstage-rechner",
    "titel": "Arbeitstage-Rechner",
    "beschreibung": "Arbeitstage pro Monat, Jahr oder Zeitraum berechnen — mit Feiertagen nach Bundesland und individueller Wochenarbeitszeit.",
    "kategorie": "Arbeit & Recht",
    "kategorieSlug": "arbeit",
    "keywords": [
      "arbeitstage rechner",
      "arbeitstage 2026",
      "arbeitstage pro monat",
      "werktage berechnen",
      "feiertage 2026",
      "brückentage 2026",
      "arbeitstage bundesland"
    ],
    "icon": "📅"
  },
  {
    "slug": "unterhaltsrechner",
    "titel": "Unterhaltsrechner",
    "beschreibung": "Kindesunterhalt berechnen nach Düsseldorfer Tabelle 2026 — mit Kindergeld-Verrechnung und Mangelfallberechnung.",
    "kategorie": "Arbeit & Recht",
    "kategorieSlug": "arbeit",
    "keywords": [
      "unterhaltsrechner",
      "kindesunterhalt berechnen",
      "düsseldorfer tabelle 2026",
      "unterhalt 2026",
      "mangelfall",
      "selbstbehalt unterhalt",
      "kindergeld verrechnung"
    ],
    "icon": "⚖️"
  },
  {
    "slug": "arbeitslosengeld-rechner",
    "titel": "Arbeitslosengeld-Rechner",
    "beschreibung": "Arbeitslosengeld I berechnen: Höhe, Dauer und Auszahlungsbetrag basierend auf dem letzten Gehalt.",
    "kategorie": "Finanzen",
    "kategorieSlug": "finanzen",
    "keywords": [
      "arbeitslosengeld rechner",
      "alg 1 rechner",
      "alg i 2026",
      "arbeitslosengeld berechnen",
      "bezugsdauer alg",
      "leistungsentgelt",
      "sperrzeit"
    ],
    "icon": "💶"
  },
  {
    "slug": "elternzeit-rechner",
    "titel": "Elternzeit-Rechner",
    "beschreibung": "Elternzeit berechnen: Anspruch, Aufteilung zwischen Partnern, Fristen und Meldetermine.",
    "kategorie": "Arbeit & Recht",
    "kategorieSlug": "arbeit",
    "keywords": [
      "elternzeit rechner",
      "elternzeit berechnen",
      "elternzeit anmelden",
      "elternzeit fristen",
      "elternzeit dauer",
      "elternzeit partnermonate",
      "kündigungsschutz elternzeit",
      "elternzeit aufteilen"
    ],
    "icon": "👶"
  },
  {
    "slug": "ehegattenunterhalt-rechner",
    "titel": "Ehegattenunterhalt-Rechner",
    "beschreibung": "Ehegattenunterhalt berechnen: Trennungsunterhalt und nachehelicher Unterhalt nach der 3/7-Methode mit Selbstbehalt-Check.",
    "kategorie": "Arbeit & Recht",
    "kategorieSlug": "arbeit",
    "keywords": [
      "ehegattenunterhalt",
      "trennungsunterhalt berechnen",
      "nachehelicher unterhalt",
      "3/7 methode",
      "selbstbehalt ehegatte",
      "differenzmethode unterhalt",
      "unterhalt scheidung"
    ],
    "icon": "⚖️"
  },
  {
    "slug": "rezept-umrechner",
    "titel": "Rezept-Umrechner",
    "beschreibung": "Rezept auf beliebige Portionen umrechnen: Zutatenmengen automatisch skalieren mit intelligenter Rundung.",
    "kategorie": "Kochen & Ernährung",
    "kategorieSlug": "kochen",
    "keywords": [
      "rezept umrechner",
      "rezept portionen umrechnen",
      "rezept verdoppeln",
      "rezept halbieren",
      "zutaten umrechnen",
      "portionen skalieren",
      "rezeptmengen anpassen",
      "rezept für 6 personen",
      "kochen rechner"
    ],
    "icon": "📝"
  },
  {
    "slug": "cups-umrechner",
    "titel": "Cups-Umrechner",
    "beschreibung": "Cups in Gramm und Milliliter umrechnen: Zutatspezifische Dichten für amerikanische Rezepte — Mehl, Zucker, Butter etc.",
    "kategorie": "Kochen & Ernährung",
    "kategorieSlug": "kochen",
    "keywords": [
      "cups umrechner",
      "cup in gramm",
      "cup in ml",
      "1 cup mehl in gramm",
      "1 cup zucker",
      "amerikanische rezepte umrechnen",
      "tablespoon in ml",
      "teaspoon in ml",
      "us cup",
      "fl oz in ml"
    ],
    "icon": "🥣"
  },
  {
    "slug": "backform-umrechner",
    "titel": "Backform-Umrechner",
    "beschreibung": "Backform umrechnen: Rund ↔ eckig ↔ Kasten, Teigmenge anpassen, Flächenvergleich mit Umrechnungsfaktor.",
    "kategorie": "Kochen & Ernährung",
    "kategorieSlug": "kochen",
    "keywords": [
      "backform umrechner",
      "springform umrechnen",
      "26 cm in 20 cm",
      "rund in eckig backform",
      "kastenform umrechnen",
      "backform größen",
      "teigmenge anpassen",
      "backform faktor",
      "backform vergleich"
    ],
    "icon": "🎂"
  },
  {
    "slug": "backzeit-rechner",
    "titel": "Backzeit-Rechner",
    "beschreibung": "Backzeit und Temperatur anpassen: Umluft ↔ Ober-/Unterhitze, Gasmark, Formgröße, Faustregeln.",
    "kategorie": "Kochen & Ernährung",
    "kategorieSlug": "kochen",
    "keywords": [
      "backzeit rechner",
      "umluft in ober unterhitze",
      "backzeit umrechnen",
      "gasmark umrechnen",
      "backzeit anpassen",
      "backtemperatur umrechnen",
      "umluft rechner",
      "backzeit andere form",
      "backofen temperatur umrechnen"
    ],
    "icon": "⏲️"
  },
  {
    "slug": "kochzeit-rechner",
    "titel": "Kochzeit-Rechner",
    "beschreibung": "Kochzeit für Ei, Nudeln, Reis, Kartoffeln und Gemüse: Sorten-Datenbank mit Schritt-für-Schritt-Anleitungen.",
    "kategorie": "Kochen & Ernährung",
    "kategorieSlug": "kochen",
    "keywords": [
      "kochzeit rechner",
      "eier kochen minuten",
      "nudeln kochzeit",
      "reis kochzeit",
      "kartoffeln kochen",
      "gemüse garzeit",
      "ei weich wachsweich hart",
      "al dente",
      "perfektes ei"
    ],
    "icon": "⏱️"
  },
  {
    "slug": "hefe-umrechner",
    "titel": "Hefe-Umrechner",
    "beschreibung": "Hefe umrechnen: Frischhefe ↔ Trockenhefe ↔ Lievito Madre mit Mengentabellen und Verarbeitungstipps.",
    "kategorie": "Kochen & Ernährung",
    "kategorieSlug": "kochen",
    "keywords": [
      "hefe umrechner",
      "frischhefe trockenhefe",
      "hefe umrechnen",
      "wie viel hefe für 500g mehl",
      "lievito madre umrechnen",
      "hefe würfel trocken",
      "hefe päckchen",
      "trockenhefe menge",
      "hefe-ersatz"
    ],
    "icon": "🥖"
  },
  {
    "slug": "pace-rechner",
    "titel": "Pace-Rechner",
    "beschreibung": "Pace, Zeit oder Distanz beim Laufen berechnen: min/km, km/h, Split-Zeiten und Zielzeit-Tabellen.",
    "kategorie": "Sport & Fitness",
    "kategorieSlug": "sport",
    "keywords": [
      "pace rechner",
      "pace berechnen laufen",
      "min/km rechner",
      "laufgeschwindigkeit",
      "marathon pace",
      "halbmarathon pace",
      "pace in km/h",
      "split zeiten laufen",
      "laufzeit rechner"
    ],
    "icon": "🏃"
  },
  {
    "slug": "herzfrequenz-zonen-rechner",
    "titel": "Herzfrequenz-Zonen-Rechner",
    "beschreibung": "Trainingszonen berechnen: HFmax nach Tanaka und Karvonen, 5 Zonen, 80/20-Training und Fettverbrennungszone.",
    "kategorie": "Sport & Fitness",
    "kategorieSlug": "sport",
    "keywords": [
      "herzfrequenz zonen",
      "trainingszonen rechner",
      "karvonen formel",
      "hfmax berechnen",
      "maximale herzfrequenz",
      "fettverbrennungszone",
      "puls trainingszonen",
      "80/20 training",
      "herzfrequenz laufen"
    ],
    "icon": "❤️"
  }
];

export const beliebteRechnerSlugs: string[] = ["prozentrechner","brutto-netto-rechner","mwst-rechner","bmi-rechner","dreisatz-rechner"];

export function getRechnerByKategorie(kategorieSlug: string): RechnerLight[] {
  return rechner.filter(r => r.kategorieSlug === kategorieSlug);
}
