'use client';

/**
 * Client-Wrapper für die 170 Rechner-Components.
 *
 * Bei Verwendung in einer Server-Component (`app/[kategorie]/[rechner]/page.tsx`)
 * sorgt das `'use client'`-Pragma dafür, dass die `dynamic()`-Imports als echte
 * Code-Splits behandelt werden — pro Slug ein eigener Chunk. Vorher wurden alle
 * 170 Components in das Page-Bundle gebündelt (~2,1 MB Chunk, T1-Befund C1).
 *
 * Wichtig:
 * - `ssr: true` (Default) — SSR-Sichtbarkeit für Crawler bleibt erhalten
 * - Lookup-Map muss vollständig sein; fehlende Slugs liefern `null`
 * - SSOT-Drift-Schutz übernimmt scripts/slug-drift-scan.mjs (Prebuild-Hook):
 *   Eine RechnerConfig ohne entsprechende RECHNER_MAP-Entry bzw. eine
 *   Map-Entry ohne Component-File würde dort Build-Break auslösen.
 */
import dynamic from 'next/dynamic';
import type { ComponentType } from 'react';

const RECHNER_MAP: Record<string, ComponentType> = {
  'prozentrechner': dynamic(() => import('@/components/rechner/Prozentrechner')),
  'brutto-netto-rechner': dynamic(() => import('@/components/rechner/BruttoNettoRechner')),
  'mwst-rechner': dynamic(() => import('@/components/rechner/MwStRechner')),
  'dreisatz-rechner': dynamic(() => import('@/components/rechner/DreisatzRechner')),
  'bmi-rechner': dynamic(() => import('@/components/rechner/BmiRechner')),
  'spritkosten-rechner': dynamic(() => import('@/components/rechner/SpritkostenRechner')),
  'kw-ps-umrechner': dynamic(() => import('@/components/rechner/KwPsRechner')),
  'kfz-steuer-rechner': dynamic(() => import('@/components/rechner/KfzSteuerRechner')),
  'zinsrechner': dynamic(() => import('@/components/rechner/ZinsRechner')),
  'tagerechner': dynamic(() => import('@/components/rechner/TageRechner')),
  'elterngeld-rechner': dynamic(() => import('@/components/rechner/ElterngeldRechner')),
  'buergergeld-rechner': dynamic(() => import('@/components/rechner/BuergergeldRechner')),
  'stundenlohn-rechner': dynamic(() => import('@/components/rechner/StundenlohnRechner')),
  'sparrechner': dynamic(() => import('@/components/rechner/SparRechner')),
  'inflationsrechner': dynamic(() => import('@/components/rechner/InflationsRechner')),
  'stromkosten-rechner': dynamic(() => import('@/components/rechner/StromkostenRechner')),
  'nebenkosten-rechner': dynamic(() => import('@/components/rechner/NebenkostenRechner')),
  'mietrechner': dynamic(() => import('@/components/rechner/MietrechnerRechner')),
  'heizkosten-rechner': dynamic(() => import('@/components/rechner/HeizkostenRechner')),
  'grunderwerbsteuer-rechner': dynamic(() => import('@/components/rechner/GrunderwerbsteuerRechner')),
  'tapetenbedarf-rechner': dynamic(() => import('@/components/rechner/TapetenbedarfRechner')),
  'quadratmeter-rechner': dynamic(() => import('@/components/rechner/QuadratmeterRechner')),
  'bruchrechner': dynamic(() => import('@/components/rechner/BruchRechner')),
  'einheiten-umrechner': dynamic(() => import('@/components/rechner/EinheitenRechner')),
  'notenschluessel-rechner': dynamic(() => import('@/components/rechner/NotenschluesselRechner')),
  'durchschnitt-rechner': dynamic(() => import('@/components/rechner/DurchschnittRechner')),
  'wissenschaftlicher-taschenrechner': dynamic(() => import('@/components/rechner/TaschenrechnerRechner')),
  'arbeitszeitrechner': dynamic(() => import('@/components/rechner/ArbeitszeitRechner')),
  'urlaubstage-rechner': dynamic(() => import('@/components/rechner/UrlaubstageRechner')),
  'ueberstunden-rechner': dynamic(() => import('@/components/rechner/UeberstundenRechner')),
  'pendlerpauschale-rechner': dynamic(() => import('@/components/rechner/PendlerpauschaleRechner')),
  'promillerechner': dynamic(() => import('@/components/rechner/PromilleRechner')),
  'rabattrechner': dynamic(() => import('@/components/rechner/RabattRechner')),
  'gehaltsvergleich': dynamic(() => import('@/components/rechner/GehaltsvergleichRechner')),
  'countdown': dynamic(() => import('@/components/rechner/CountdownRechner')),
  'lebenszeit-rechner': dynamic(() => import('@/components/rechner/LebenszeitRechner')),
  'streaming-kosten-rechner': dynamic(() => import('@/components/rechner/StreamingKostenRechner')),
  'raucher-rechner': dynamic(() => import('@/components/rechner/RaucherRechner')),
  'wahrer-stundenlohn': dynamic(() => import('@/components/rechner/WahrerStundenlohnRechner')),
  'schlaf-rechner': dynamic(() => import('@/components/rechner/SchlafRechner')),
  'kaffee-kosten-rechner': dynamic(() => import('@/components/rechner/KaffeeKostenRechner')),
  'lieferservice-rechner': dynamic(() => import('@/components/rechner/LieferserviceRechner')),
  'abo-rechner': dynamic(() => import('@/components/rechner/AboRechner')),
  'handykosten-rechner': dynamic(() => import('@/components/rechner/HandykostenRechner')),
  'rechtsschutz-rechner': dynamic(() => import('@/components/rechner/RechtsschutzRechner')),
  'steuererstattung-rechner': dynamic(() => import('@/components/rechner/SteuererstattungRechner')),
  'stromvergleich-rechner': dynamic(() => import('@/components/rechner/StromvergleichRechner')),
  'freelancer-stundensatz-rechner': dynamic(() => import('@/components/rechner/FreelancerStundensatzRechner')),
  'bussgeldrechner': dynamic(() => import('@/components/rechner/BussgeldRechner')),
  'kreditrechner': dynamic(() => import('@/components/rechner/KreditRechner')),
  'kalorienrechner': dynamic(() => import('@/components/rechner/KalorienRechner')),
  'geburtstermin-rechner': dynamic(() => import('@/components/rechner/GeburtsterminRechner')),
  'idealgewicht-rechner': dynamic(() => import('@/components/rechner/IdealgewichtRechner')),
  'protein-rechner': dynamic(() => import('@/components/rechner/ProteinRechner')),
  'kuendigungsfrist-rechner': dynamic(() => import('@/components/rechner/KuendigungsfristRechner')),
  'etf-sparplanrechner': dynamic(() => import('@/components/rechner/EtfSparplanRechner')),
  'teilzeit-rechner': dynamic(() => import('@/components/rechner/TeilzeitRechner')),
  'abfindungsrechner': dynamic(() => import('@/components/rechner/AbfindungsRechner')),
  'mutterschutz-rechner': dynamic(() => import('@/components/rechner/MutterschutzRechner')),
  'baufinanzierung-rechner': dynamic(() => import('@/components/rechner/BaufinanzierungRechner')),
  'rentenrechner': dynamic(() => import('@/components/rechner/RentenRechner')),
  'wasserbedarf-rechner': dynamic(() => import('@/components/rechner/WasserbedarfRechner')),
  'umzugskosten-rechner': dynamic(() => import('@/components/rechner/UmzugskostenRechner')),
  'trinkgeld-rechner': dynamic(() => import('@/components/rechner/TrinkgeldRechner')),
  'koerperfett-rechner': dynamic(() => import('@/components/rechner/KoerperfettRechner')),
  'flaechenrechner': dynamic(() => import('@/components/rechner/FlaechenRechner')),
  'mietrendite-rechner': dynamic(() => import('@/components/rechner/MietrenditeRechner')),
  'geburtstag-rechner': dynamic(() => import('@/components/rechner/GeburtstagRechner')),
  'prozentuale-veraenderung-rechner': dynamic(() => import('@/components/rechner/ProzVeraenderungRechner')),
  'splitting-rechner': dynamic(() => import('@/components/rechner/SplittingRechner')),
  'autokosten-rechner': dynamic(() => import('@/components/rechner/AutokostenRechner')),
  'wohngeld-rechner': dynamic(() => import('@/components/rechner/WohngeldRechner')),
  'bafoeg-rechner': dynamic(() => import('@/components/rechner/BafoegRechner')),
  'aufstiegs-bafoeg-rechner': dynamic(() => import('@/components/rechner/AfbgRechner')),
  'kindergeld-rechner': dynamic(() => import('@/components/rechner/KindergeldRechner')),
  'pflegegeld-rechner': dynamic(() => import('@/components/rechner/PflegegeldRechner')),
  'ssw-rechner': dynamic(() => import('@/components/rechner/SswRechner')),
  'erbschaftsteuer-rechner': dynamic(() => import('@/components/rechner/ErbschaftsteuerRechner')),
  'scheidungskosten-rechner': dynamic(() => import('@/components/rechner/ScheidungskostenRechner')),
  'indexmiete-rechner': dynamic(() => import('@/components/rechner/IndexmieteRechner')),
  'minijob-rechner': dynamic(() => import('@/components/rechner/MinijobRechner')),
  'waermepumpen-rechner': dynamic(() => import('@/components/rechner/WaermepumpeRechner')),
  'gehaltserhoehung-rechner': dynamic(() => import('@/components/rechner/GehaltserhoehungRechner')),
  'zugewinnausgleich-rechner': dynamic(() => import('@/components/rechner/ZugewinnausgleichRechner')),
  'volumenrechner': dynamic(() => import('@/components/rechner/VolumenRechner')),
  'leasing-rechner': dynamic(() => import('@/components/rechner/LeasingRechner')),
  'skontorechner': dynamic(() => import('@/components/rechner/SkontoRechner')),
  'krankengeld-rechner': dynamic(() => import('@/components/rechner/KrankengeldRechner')),
  'abi-rechner': dynamic(() => import('@/components/rechner/AbiRechner')),
  'photovoltaik-rechner': dynamic(() => import('@/components/rechner/PhotovoltaikRechner')),
  'schwangerschaft-gewicht-rechner': dynamic(() => import('@/components/rechner/SchwangerschaftGewichtRechner')),
  'uhrzeitrechner': dynamic(() => import('@/components/rechner/UhrzeitRechner')),
  'gmbh-geschaeftsfuehrer-rechner': dynamic(() => import('@/components/rechner/GmbhGfRechner')),
  'arbeitstage-rechner': dynamic(() => import('@/components/rechner/ArbeitstageRechner')),
  'binaer-rechner': dynamic(() => import('@/components/rechner/BinaerRechner')),
  'dachflaechen-rechner': dynamic(() => import('@/components/rechner/DachflaechenRechner')),
  'hundejahre-rechner': dynamic(() => import('@/components/rechner/HundejahreRechner')),
  'zyklusrechner': dynamic(() => import('@/components/rechner/ZyklusRechner')),
  'hochrechner': dynamic(() => import('@/components/rechner/HochRechner')),
  'malerkosten-rechner': dynamic(() => import('@/components/rechner/MalerkostenRechner')),
  'waehrungsrechner': dynamic(() => import('@/components/rechner/WaehrungsRechner')),
  'alkohol-abbau-rechner': dynamic(() => import('@/components/rechner/AlkoholAbbauRechner')),
  'unterhaltsrechner': dynamic(() => import('@/components/rechner/UnterhaltsRechner')),
  'arbeitslosengeld-rechner': dynamic(() => import('@/components/rechner/ArbeitslosengeldRechner')),
  'grundsteuer-rechner': dynamic(() => import('@/components/rechner/GrundsteuerRechner')),
  'midijob-rechner': dynamic(() => import('@/components/rechner/MidijobRechner')),
  'firmenwagen-rechner': dynamic(() => import('@/components/rechner/FirmenwagenRechner')),
  'elternzeit-rechner': dynamic(() => import('@/components/rechner/ElternzeitRechner')),
  'witwenrente-rechner': dynamic(() => import('@/components/rechner/WitwenrenteRechner')),
  'kurzarbeitergeld-rechner': dynamic(() => import('@/components/rechner/KurzarbeitergeldRechner')),
  'riester-rechner': dynamic(() => import('@/components/rechner/RiesterRechner')),
  'fuehrerschein-rechner': dynamic(() => import('@/components/rechner/FuehrerscheinRechner')),
  'nettolohn-optimierer': dynamic(() => import('@/components/rechner/NettolohnOptimiererRechner')),
  'mietpreisbremse-rechner': dynamic(() => import('@/components/rechner/MietpreisbremseRechner')),
  'kapitalertragsteuer-rechner': dynamic(() => import('@/components/rechner/KapitalertragsteuerRechner')),
  'schuhgroessen-rechner': dynamic(() => import('@/components/rechner/SchuhgroessenRechner')),
  'reichweiten-rechner': dynamic(() => import('@/components/rechner/ReichweitenRechner')),
  'poolkosten-rechner': dynamic(() => import('@/components/rechner/PoolkostenRechner')),
  'pythagoras-rechner': dynamic(() => import('@/components/rechner/PythagorasRechner')),
  'gleichungsrechner': dynamic(() => import('@/components/rechner/GleichungsloeserRechner')),
  'kleidergroessen-rechner': dynamic(() => import('@/components/rechner/KleidergroessenRechner')),
  'ehegattenunterhalt-rechner': dynamic(() => import('@/components/rechner/EhegattenunterhaltRechner')),
  'afa-rechner': dynamic(() => import('@/components/rechner/AfaRechner')),
  'vorfaelligkeitsentschaedigung-rechner': dynamic(() => import('@/components/rechner/VorfaelligkeitsentschaedigungRechner')),
  'energiekosten-rechner': dynamic(() => import('@/components/rechner/EnergiekostenRechner')),
  'betriebskosten-rechner': dynamic(() => import('@/components/rechner/BetriebskostenRechner')),
  'fliesenbedarf-rechner': dynamic(() => import('@/components/rechner/FliesenbedarfRechner')),
  'laminat-rechner': dynamic(() => import('@/components/rechner/LaminatRechner')),
  'whr-rechner': dynamic(() => import('@/components/rechner/WhrRechner')),
  'mwst-rueckerstattung-rechner': dynamic(() => import('@/components/rechner/MwStRueckerstattungRechner')),
  'primzahl-rechner': dynamic(() => import('@/components/rechner/PrimzahlRechner')),
  'quersumme-rechner': dynamic(() => import('@/components/rechner/QuersummeRechner')),
  'potenz-rechner': dynamic(() => import('@/components/rechner/PotenzRechner')),
  'ggt-kgv-rechner': dynamic(() => import('@/components/rechner/GgtKgvRechner')),
  'zufallszahl-generator': dynamic(() => import('@/components/rechner/ZufallszahlRechner')),
  'blutdruck-rechner': dynamic(() => import('@/components/rechner/BlutdruckRechner')),
  'schritte-rechner': dynamic(() => import('@/components/rechner/SchritteRechner')),
  'sonnenschutz-rechner': dynamic(() => import('@/components/rechner/SonnenschutzRechner')),
  'reisekosten-rechner': dynamic(() => import('@/components/rechner/ReisekostenRechner')),
  'zeitwert-rechner': dynamic(() => import('@/components/rechner/ZeitwertRechner')),
  'fahrrad-rahmengroesse-rechner': dynamic(() => import('@/components/rechner/FahrradRahmenRechner')),
  'taxi-rechner': dynamic(() => import('@/components/rechner/TaxiRechner')),
  'beton-rechner': dynamic(() => import('@/components/rechner/BetonRechner')),
  'estrich-rechner': dynamic(() => import('@/components/rechner/EstrichRechner')),
  'balkon-solar-rechner': dynamic(() => import('@/components/rechner/BalkonSolarRechner')),
  'noten-international': dynamic(() => import('@/components/rechner/NotenInternationalRechner')),
  'steuerprogression-rechner': dynamic(() => import('@/components/rechner/SteuerprogressionsRechner')),
  'budget-rechner': dynamic(() => import('@/components/rechner/BudgetRechner')),
  'spenden-rechner': dynamic(() => import('@/components/rechner/SpendenRechner')),
  'nebenjob-rechner': dynamic(() => import('@/components/rechner/NebenjobRechner')),
  'schenkungssteuer-rechner': dynamic(() => import('@/components/rechner/SchenkungssteuerRechner')),
  'gewerbesteuer-rechner': dynamic(() => import('@/components/rechner/GewerbesteuerRechner')),
  'einkommensteuer-rechner': dynamic(() => import('@/components/rechner/EinkommensteuerRechner')),
  'steuerklassen-vergleich-rechner': dynamic(() => import('@/components/rechner/SteuerklassenVergleichRechner')),
  'pfaendungsrechner': dynamic(() => import('@/components/rechner/PfaendungRechner')),
  'lohnsteuer-rechner': dynamic(() => import('@/components/rechner/LohnsteuerRechner')),
  'rezept-umrechner': dynamic(() => import('@/components/rechner/RezeptUmrechner')),
  'cups-umrechner': dynamic(() => import('@/components/rechner/CupsUmrechner')),
  'pace-rechner': dynamic(() => import('@/components/rechner/PaceRechner')),
  'herzfrequenz-zonen-rechner': dynamic(() => import('@/components/rechner/HerzfrequenzZonenRechner')),
  'backform-umrechner': dynamic(() => import('@/components/rechner/BackformUmrechner')),
  'backzeit-rechner': dynamic(() => import('@/components/rechner/BackzeitRechner')),
  'kochzeit-rechner': dynamic(() => import('@/components/rechner/KochzeitRechner')),
  'hefe-umrechner': dynamic(() => import('@/components/rechner/HefeUmrechner')),
  'pizzateig-rechner': dynamic(() => import('@/components/rechner/PizzateigRechner')),
  'brotback-rechner': dynamic(() => import('@/components/rechner/BrotbackRechner')),
  'alkoholgehalt-rechner': dynamic(() => import('@/components/rechner/AlkoholgehaltRechner')),
  'naehrwert-rechner': dynamic(() => import('@/components/rechner/NaehrwertRechner')),
  'zucker-umrechner': dynamic(() => import('@/components/rechner/ZuckerUmrechner')),
  'gefrierdauer-rechner': dynamic(() => import('@/components/rechner/GefrierdauerRechner')),
};

export default function RechnerLoader({ slug }: { slug: string }) {
  const Component = RECHNER_MAP[slug];
  if (!Component) return null;
  return <Component />;
}
