/**
 * AUTO-GENERATED by scripts/generate-tipp-constants.ts — DO NOT EDIT MANUALLY.
 * Regenerate: npx tsx scripts/generate-tipp-constants.ts (läuft im prebuild)
 *
 * Statische Build-Time-Konstanten für TippDesTages-Mindestlohn-Beispiel.
 * Verhindert dass berechneBruttoNetto (→ decimal.js) im Client-Bundle landet.
 */

/** Mindestlohn 2026 in €/Std (aus lib/berechnungen/mindestlohn.ts MINDESTLOHN). */
export const MINDESTLOHN_TIPP_STUNDE = 13.9;

/** Vollzeit-Brutto pro Monat = MINDESTLOHN × 40 × 4,33, gerundet. */
export const MINDESTLOHN_TIPP_BRUTTO = 2407;

/** Netto in SK 1, NRW, GKV mit Ø-Zusatzbeitrag, ohne Kirchensteuer. */
export const MINDESTLOHN_TIPP_NETTO = 1711;
