/**
 * Generator für lib/tipp-konstanten.ts (TippDesTages-Mindestlohn-Beispiel).
 *
 * Berechnet zur Build-Time einmal Brutto + Netto für den aktuellen
 * MINDESTLOHN-Wert via `berechneBruttoNetto` und schreibt die Werte als
 * statische Konstanten in eine TS-Datei. So fliegt `decimal.js` (296 KB
 * Source-Lib, ~100 KB minified) aus dem Homepage-Initial-Bundle.
 *
 * Beim 01.01.2027-Mindestlohn-Wechsel (13,90 → 14,60 € via Stichtag-Switch
 * in mindestlohn.ts) wird beim nächsten Build automatisch der neue Wert
 * eingebaut — keine manuelle Pflege nötig.
 *
 * Lauft im prebuild-Hook (package.json) gemeinsam mit generate-client-data.
 */
import { writeFileSync } from 'fs';
import { MINDESTLOHN } from '../lib/berechnungen/mindestlohn';
import { berechneBruttoNetto } from '../lib/berechnungen/brutto-netto';
import { KV_ZUSATZBEITRAG_VOLL_DURCHSCHNITT_2026_PROZENT } from '../lib/berechnungen/sv-parameter';

const mindestlohnBrutto = Math.round(MINDESTLOHN * 40 * 4.33);
const mindestlohnNetto = Math.round(
  berechneBruttoNetto({
    bruttoMonat: mindestlohnBrutto,
    steuerklasse: 1,
    kirchensteuer: false,
    kirchensteuersatz: 9,
    kinderfreibetraege: 0,
    bundesland: 'NW',
    kvArt: 'gesetzlich',
    kvZusatzbeitrag: KV_ZUSATZBEITRAG_VOLL_DURCHSCHNITT_2026_PROZENT,
    kvPrivatBeitrag: 0,
    rvBefreit: false,
    abrechnungszeitraum: 'monat',
  }).nettoMonat,
);

const content = `/**
 * AUTO-GENERATED by scripts/generate-tipp-constants.ts — DO NOT EDIT MANUALLY.
 * Regenerate: npx tsx scripts/generate-tipp-constants.ts (läuft im prebuild)
 *
 * Statische Build-Time-Konstanten für TippDesTages-Mindestlohn-Beispiel.
 * Verhindert dass berechneBruttoNetto (→ decimal.js) im Client-Bundle landet.
 */

/** Mindestlohn 2026 in €/Std (aus lib/berechnungen/mindestlohn.ts MINDESTLOHN). */
export const MINDESTLOHN_TIPP_STUNDE = ${MINDESTLOHN};

/** Vollzeit-Brutto pro Monat = MINDESTLOHN × 40 × 4,33, gerundet. */
export const MINDESTLOHN_TIPP_BRUTTO = ${mindestlohnBrutto};

/** Netto in SK 1, NRW, GKV mit Ø-Zusatzbeitrag, ohne Kirchensteuer. */
export const MINDESTLOHN_TIPP_NETTO = ${mindestlohnNetto};
`;

writeFileSync('lib/tipp-konstanten.ts', content);
console.log(`✅ Generated lib/tipp-konstanten.ts (Brutto ${mindestlohnBrutto} € / Netto ${mindestlohnNetto} €)`);
