/**
 * Generates lib/rechner-config/client-data.ts — a lightweight module
 * containing only the fields that client components need (slug, titel,
 * beschreibung, kategorie, kategorieSlug, keywords, icon).
 *
 * WHY: The full rechner-config is ~950 KB (SEO texts, FAQ arrays).
 * Client components (Footer, Header, SearchBar, FeedbackClient) that
 * import it cause a bloated client bundle, leading to silent truncation
 * and wrong rechner counts. This lightweight export avoids that.
 *
 * RUN: npx tsx scripts/generate-client-data.ts
 * WHEN: After adding/removing/renaming rechner in lib/rechner-config/*.ts
 */

import { writeFileSync } from 'fs';
import { resolve } from 'path';
import { rechner, kategorien, beliebteRechnerSlugs } from '../lib/rechner-config/index';

const light = rechner.map(r => ({
  slug: r.slug,
  titel: r.titel,
  beschreibung: r.beschreibung,
  kategorie: r.kategorie,
  kategorieSlug: r.kategorieSlug,
  keywords: r.keywords,
  icon: r.icon,
}));

// Kategorien explizit light — ohne einleitung (nur Server-Component braucht das,
// Client-Bundle würde unnötig um ~10 KB aufgebläht + Type-Mismatch zum Inline-Interface).
const kategorienLight = kategorien.map(k => ({
  slug: k.slug,
  name: k.name,
  beschreibung: k.beschreibung,
  icon: k.icon,
  metaTitle: k.metaTitle,
  metaDescription: k.metaDescription,
}));

const output = `/**
 * AUTO-GENERATED by scripts/generate-client-data.ts — DO NOT EDIT MANUALLY.
 * Regenerate: npx tsx scripts/generate-client-data.ts
 * Generated: ${new Date().toISOString().slice(0, 10)}
 *
 * Lightweight rechner data for client components (Footer, Header, SearchBar).
 * Excludes heavy fields: erklaerung (~600 words each), faq, formel, beispiel,
 * metaTitle, metaDescription — saving ~900 KB from the client bundle.
 */

export interface RechnerLight {
  slug: string;
  titel: string;
  beschreibung: string;
  kategorie: string;
  kategorieSlug: string;
  keywords: string[];
  icon: string;
}

export interface KategorieConfig {
  slug: string;
  name: string;
  beschreibung: string;
  icon: string;
  metaTitle: string;
  metaDescription: string;
}

export const kategorien: KategorieConfig[] = ${JSON.stringify(kategorienLight, null, 2)};

export const rechner: RechnerLight[] = ${JSON.stringify(light, null, 2)};

export const beliebteRechnerSlugs: string[] = ${JSON.stringify(beliebteRechnerSlugs)};

export function getRechnerByKategorie(kategorieSlug: string): RechnerLight[] {
  return rechner.filter(r => r.kategorieSlug === kategorieSlug);
}
`;

const outPath = resolve(__dirname, '..', 'lib', 'rechner-config', 'client-data.ts');
writeFileSync(outPath, output, 'utf-8');

console.log(`✅ Generated ${outPath}`);
console.log(`   ${rechner.length} rechner, ${kategorien.length} kategorien`);
console.log(`   File size: ~${Math.round(output.length / 1024)} KB (vs ~950 KB full config)`);
